giantswarm/azure-operator

- service/arm_templates/network_setup.json
- service/arm_templates/security_groups_setup.json
Basic template that creates 1 virtuals networks, 2 subnets and 2 security groups (one for each subnet)
Next step:
- Create the routeTables
- Add them to the resources.properties.subnets.properties object
> Add basic network setup ARM template

- service/resource/deployment/deployment.go
- service/resource/deployment/error.go
- service/resource/deployment/resource.go
- service/resource/deployment/resource_test.go
- service/resource/deployment/spec.go
- service/resource/resourcegroup/resource.go
- service/service.go
Towards #6 
This PR adds the Deployment resource which deploys ARM templates. This PR implements getting the current deployments for the resource group. Creating deployments will come in a later PR.
> Add deployment resource

- examples/local/README.md
- examples/local/cluster.tmpl.yaml
- examples/local/configmap.tmpl.yaml
Updates local setup guide to configure the Active Directory Service Principal for authenticating with the Azure APIs. Also updates the cluster template with recent changes.
> Update local setup guide

- service/resource/deployment/deployment.go
- service/resource/deployment/resource.go
- service/resource/deployment/spec.go
- service/resource/deployment/template.go
- service/resource/deployment/template_test.go
- service/service.go
* extract URI generating functions and test them
* remove unused constants
> fix template URI mess

- service/cloudconfig/template.go
Waiting for Azure vault and its secrets to be available before trying to fetch them
> secrets fetching script

- client/azure.go
- client/fakeclient/azure.go
- main.go
- service/cloudconfig/service.go
- service/operator/framework.go
- service/operator/service.go
- service/resource/deployment/resource.go
- service/resource/deployment/resource_test.go
- service/resource/resourcegroup/resource.go
- service/resource/resourcegroup/resource_test.go
- service/service.go
We need AzureConfig inside CloudConfig to finish https://github.com/giantswarm/azure-operator/pull/54
> service: provide AzureConfig to CloudConfig

- service/cloudconfig/cloud_config.go
- service/cloudconfig/template.go
- service/key/key.go
- service/key/key_test.go
this config used by Kubernetes Azure cloud provider.
> Adds Azure cloud provider config

- service/arm_templates/main.json
- service/arm_templates/route_table_setup.json
- service/arm_templates/virtual_network_setup.json
Creates a route table required by calico.
I tested it.
> arm_templates: add route table

- service/arm_templates/main.json
Quick fixes to allow DNS records to be created correctly.
> Fix dns_setups dnsZone parameters

- service/cloudconfig/template.go
Just removes back quotes that were brought back after auto-merge.
> Fix CI after improper auto-merge

- service/cloudconfig/master_extension.go
- service/cloudconfig/render.go
- service/cloudconfig/render_test.go
- service/cloudconfig/template.go
- service/cloudconfig/types.go
- service/cloudconfig/worker_extension.go
> Adds mount units for etcd and docker disks.

- service/arm_templates/availability_sets_setup.json
- service/arm_templates/certificates.json
- service/arm_templates/dns_a_setup.json
- service/arm_templates/dns_cname_setup.json
- service/arm_templates/main.json
- service/arm_templates/node_setup.json
- service/arm_templates/public_load_balancer_setup.json
- service/arm_templates/route_table_setup.json
- service/arm_templates/security_groups_setup.json
- service/arm_templates/virtual_network_setup.json
this change adds Giant Swarm provider ID as a tag that will be used by Microsoft.
Provider ID and format was sent to us by Microsoft.
> Adds Giant Swarm provider tag

- helm/azure-operator-chart/templates/deployment.yaml
- helm/azure-operator-chart/templates/psp.yaml
- helm/azure-operator-chart/templates/rbac.yaml
- helm/azure-operator-chart/templates/service-account.yaml
Towards [#2296](https://github.com/giantswarm/giantswarm/issues/2296)
Although we don't have yet an environment with services running for Azure, I have left this PR open to track and remember the RBAC implementation. For now, I have just added namespaces and azureconfigs
> Add rbac and sa

- Gopkg.lock
- service/cloudconfig/template.go
- service/version_bundles.go
- vendor/github.com/giantswarm/k8scloudconfig/CHANGELOG.md
- vendor/github.com/giantswarm/k8scloudconfig/v_3_1_1/cloudconfig.go
- vendor/github.com/giantswarm/k8scloudconfig/v_3_1_1/cloudconfig_test.go
- vendor/github.com/giantswarm/k8scloudconfig/v_3_1_1/common_template_test.go
- vendor/github.com/giantswarm/k8scloudconfig/v_3_1_1/error.go
- vendor/github.com/giantswarm/k8scloudconfig/v_3_1_1/master_template.go
- vendor/github.com/giantswarm/k8scloudconfig/v_3_1_1/master_template_test.go
- vendor/github.com/giantswarm/k8scloudconfig/v_3_1_1/render_asset_content.go
- vendor/github.com/giantswarm/k8scloudconfig/v_3_1_1/render_asset_content_test.go
- vendor/github.com/giantswarm/k8scloudconfig/v_3_1_1/types.go
- vendor/github.com/giantswarm/k8scloudconfig/v_3_1_1/worker_template.go
- vendor/github.com/giantswarm/k8scloudconfig/v_3_1_1/worker_template_test.go
Towards https://github.com/giantswarm/aws-operator/issues/651
> Change default etcd data dir to /var/lib/etcd

- helm/azure-operator-chart/templates/rbac.yaml
Towards https://github.com/giantswarm/k8scloudconfig/issues/290
> Update rbac doc version to v1

- service/controller/v1/arm_templates/main.json
I noted that today. Tested locally.
> arm_templates: fix worker VMSS subnet

- service/controller/v1/resource/endpoints/create.go
- service/controller/v1/resource/endpoints/create_test.go
- service/controller/v1/resource/endpoints/current.go
- service/controller/v1/resource/endpoints/delete.go
- service/controller/v1/resource/endpoints/delete_test.go
- service/controller/v1/resource/endpoints/resource.go
- service/controller/v1/resource/endpoints/update.go
- service/controller/v1/resource/endpoints/update_test.go
- service/controller/v1/resource/namespace/create.go
- service/controller/v1/resource/namespace/create_test.go
- service/controller/v1/resource/namespace/current.go
- service/controller/v1/resource/namespace/current_test.go
- service/controller/v1/resource/namespace/delete.go
- service/controller/v1/resource/namespace/delete_test.go
- service/controller/v1/resource/namespace/desired.go
- service/controller/v1/resource/namespace/desired_test.go
- service/controller/v1/resource/namespace/resource.go
- service/controller/v1/resource/service/create.go
- service/controller/v1/resource/service/create_test.go
- service/controller/v1/resource/service/current.go
- service/controller/v1/resource/service/delete.go
- service/controller/v1/resource/service/delete_test.go
- service/controller/v1/resource/service/desired_test.go
- service/controller/v1/resource/service/resource.go
Closes https://github.com/giantswarm/azure-operator/issues/180
> Moves apiv1 to corev1

- Gopkg.lock
- vendor/github.com/giantswarm/k8scloudconfig/v_3_2_5/master_template.go
- vendor/github.com/giantswarm/k8scloudconfig/v_3_2_5/worker_template.go
Required for https://github.com/giantswarm/installations/pull/271
> Vendor last k8scc

- service/controller/v1/resource/deployment/deployment.go
- service/controller/v1/resource/deployment/types.go
- service/controller/v1/version_bundle.go
Towards https://github.com/giantswarm/giantswarm/issues/3021
> v1: update Contriner Linux to 1688.5.3

- helm/azure-operator-chart/templates/deployment.yaml
Towards https://github.com/giantswarm/giantswarm/issues/3022
> helm: add configmap checksum to deployment

- service/controller/v1/key/key.go
- service/controller/v1/resource/deployment/deployment.go
- service/controller/v1/resource/deployment/resource.go
- service/controller/v1/resource/deployment/resource_test.go
- service/controller/v1/resource_set.go
The problem is the cert secrets can be already deleted.
> v1: cancel deployment deletion

- Gopkg.lock
- service/controller/cluster.go
- vendor/github.com/giantswarm/operatorkit/controller/controller.go
- vendor/github.com/giantswarm/operatorkit/controller/metric.go
- vendor/github.com/giantswarm/operatorkit/controller/resource/metricsresource/crud_resource_ops_wrapper.go
- vendor/github.com/giantswarm/operatorkit/controller/resource/metricsresource/metric.go
- vendor/github.com/giantswarm/operatorkit/controller/resource/metricsresource/resource_wrapper.go
- vendor/github.com/giantswarm/operatorkit/informer/collector.go
- vendor/github.com/giantswarm/operatorkit/informer/error.go
- vendor/github.com/giantswarm/operatorkit/informer/informer.go
- vendor/github.com/giantswarm/operatorkit/informer/spec.go
Towards https://github.com/giantswarm/giantswarm/issues/3078
> Vendor update latest operatorkit

- Gopkg.lock
- service/controller/v2/cloudconfig/cloud_config.go
- service/controller/v2/cloudconfig/master_extension.go
- service/controller/v2/cloudconfig/render.go
- service/controller/v2/cloudconfig/worker_extension.go
- service/controller/v2/version_bundle.go
- vendor/github.com/giantswarm/k8scloudconfig/v_3_3_0/cloudconfig.go
- vendor/github.com/giantswarm/k8scloudconfig/v_3_3_0/error.go
- vendor/github.com/giantswarm/k8scloudconfig/v_3_3_0/master_template.go
- vendor/github.com/giantswarm/k8scloudconfig/v_3_3_0/render_asset_content.go
- vendor/github.com/giantswarm/k8scloudconfig/v_3_3_0/types.go
- vendor/github.com/giantswarm/k8scloudconfig/v_3_3_0/worker_template.go
Depends on: https://github.com/giantswarm/k8scloudconfig/pull/365
Fixes: https://github.com/giantswarm/giantswarm/issues/2865
> Update hyperkube to 1.10.2

- service/controller/v2/resource/deployment/resource.go
- service/controller/v2/resource/dnsrecord/delete.go
This PR is the start of a series of PRs towards log message improvements. The goal is to not diverge anymore from the other operators we build. This should make working across projects a lot easier.
> improves log messages

- Gopkg.lock
- service/controller/v2/resource_set.go
- vendor/github.com/giantswarm/operatorkit/controller/resource/retryresource/wrap.go
Towards https://github.com/giantswarm/giantswarm/issues/3296.
> updates vendor deps

- helm/azure-operator-chart/templates/deployment.yaml
Towards https://github.com/giantswarm/giantswarm/issues/3395
> Add release time annotation

- service/controller/v2/resource/deployment/resource.go
Towards https://github.com/giantswarm/azure-operator/issues/233.
> uses incremental deployment mode to preserve k8s LB

- service/controller/v2/arm_templates/main.json
Fixes: https://github.com/giantswarm/azure-operator/issues/231
> Add etcd disk for vmss master

- service/controller/v2/arm_templates/kubernetes_load_balancer_setup.json
forgot to add dependency. It fails sometimes without.
Initial change https://github.com/giantswarm/azure-operator/pull/249
> Fix kubernetes lb dependency

- service/controller/cluster.go
- service/controller/v3/version_bundle.go
- service/version_bundles.go
> v3: clean up changelog and set release number to 1.1.0

- client/azure_client_set.go
- client/fakeclient/azure.go
- integration/test/ready/main_test.go
- service/service.go
Towards: https://github.com/giantswarm/giantswarm/issues/3316
> BYOC client: remove AzureClientSet logger

- client/azure_client_set.go
Towards: https://github.com/giantswarm/giantswarm/issues/3316
> BYOC add VPN Gateway & Connections clients

- service/controller/cluster.go
Towards https://github.com/giantswarm/azure-operator/pull/248.
> sets resync period to 3 minutes for separated template management

- integration/test/scaling/main_test.go
Fixes https://github.com/giantswarm/azure-operator/pull/263.
> fixes scaling integration test

- service/controller/v3/debugger/debugger.go
- service/controller/v3/debugger/error.go
- service/controller/v3/key/key.go
- service/controller/v3/resource/deployment/resource.go
- service/controller/v3/resource_set.go
Fixes https://github.com/giantswarm/giantswarm/issues/3290.
> adds debugger service to inspect properties of failed deployments

- service/controller/v3/resource/instance/create.go
Follow up of https://github.com/giantswarm/azure-operator/pull/281#discussion_r206762038.
> improve minor code flaws

- service/controller/cluster.go
- service/controller/v2patch1/cloudconfig/master_extension.go
- service/controller/v2patch1/cloudconfig/render.go
- service/controller/v2patch1/cloudconfig/render_test.go
- service/controller/v2patch1/cloudconfig/template.go
- service/controller/v2patch1/cloudconfig/types.go
- service/controller/v2patch1/cloudconfig/worker_extension.go
- service/controller/v2patch1/version_bundle.go
- service/version_bundles.go
fixes: https://github.com/giantswarm/giantswarm/issues/3847
upgrade to 1.1.0 tested in `ghost`
- wire v2patch1
- cherry-pick https://github.com/giantswarm/azure-operator/pull/308
> v2patch1: Fix Azure disk mounts

- README.md
Reference (recently added) `policies/guest.tmpl.json` in README instead of using hardcoded policy.
> use policy file in README

- service/controller/cluster.go
- service/controller/v4/version_bundle.go
- service/version_bundles.go
Wire new controller v4
Previous PRs: #322 #323
> wire controller/v4

- service/controller/v4/version_bundle.go
Following https://github.com/giantswarm/installations/pull/463
> Bump v4 WIP to 2.0.0

- server/endpoint/endpoint.go
- service/controller/v4/resource/namespace/current.go
Towards https://github.com/giantswarm/giantswarm/issues/4054.
> keeps finalizers until namespace is really gone

- service/controller/v4/cloudconfig/template.go
- service/controller/v4/version_bundle.go
Part of: https://github.com/giantswarm/giantswarm/issues/3922
> Upgrade calico to 3.2.0

- service/controller/v4/resource/instance/create.go
- service/controller/v4/resource/instance/resource.go
- service/controller/v4/resource_set.go
Fixes https://github.com/giantswarm/giantswarm/issues/4169.
> adds debugger to instance resource

- Gopkg.lock
- service/controller/v4/cloudconfig/cloud_config.go
- service/controller/v4/version_bundle.go
- vendor/github.com/giantswarm/k8scloudconfig/v_3_6_0/master_template.go
- vendor/github.com/giantswarm/k8scloudconfig/v_3_6_0/types.go
Towards https://github.com/giantswarm/giantswarm/issues/1902
> Disable k8scc CoreDNS templates

- service/controller/cluster.go
- service/controller/v5/version_bundle.go
- service/version_bundles.go
Towards https://github.com/giantswarm/giantswarm/issues/4287
> wire v5, bump version and initialize changelog

- Gopkg.lock
- service/controller/v4/cloudconfig/cloud_config.go
- service/controller/v4/cloudconfig/master_extension.go
- service/controller/v4/cloudconfig/render.go
- service/controller/v4/cloudconfig/worker_extension.go
- service/controller/v4/version_bundle.go
- service/controller/v5/cloudconfig/cloud_config.go
- service/controller/v5/cloudconfig/master_extension.go
- service/controller/v5/cloudconfig/render.go
- service/controller/v5/cloudconfig/worker_extension.go
- vendor/github.com/giantswarm/k8scloudconfig/v_3_6_1/cloudconfig.go
- vendor/github.com/giantswarm/k8scloudconfig/v_3_6_1/error.go
- vendor/github.com/giantswarm/k8scloudconfig/v_3_6_1/master_template.go
- vendor/github.com/giantswarm/k8scloudconfig/v_3_6_1/render_asset_content.go
- vendor/github.com/giantswarm/k8scloudconfig/v_3_6_1/types.go
- vendor/github.com/giantswarm/k8scloudconfig/v_3_6_1/worker_template.go
- vendor/github.com/spf13/cobra/cobra/cmd/license_agpl.go
- vendor/github.com/spf13/cobra/cobra/cmd/license_apache_2.go
- vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_2.go
- vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_3.go
- vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_2.go
- vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_3.go
- vendor/github.com/spf13/cobra/cobra/cmd/license_lgpl.go
- vendor/github.com/spf13/cobra/cobra/cmd/license_mit.go
- vendor/github.com/spf13/cobra/cobra/cmd/licenses.go
Towards giantswarm/giantswarm#4287
Using k8scc `v_3_6_1` (which includes the 1.11 mem leak fix) in both `v4` and `v5`.
> Include memleak patch

- service/controller/v4/version_bundle.go
- service/controller/v5/cloudconfig/template.go
- service/controller/v5/version_bundle.go
Part of: https://github.com/giantswarm/giantswarm/issues/4159
> Added calico limits and update to 3.2.3 bugfix release

- Gopkg.lock
- service/controller/v5/cloudconfig/cloud_config.go
- service/controller/v5/cloudconfig/master_extension.go
- service/controller/v5/cloudconfig/render.go
- service/controller/v5/cloudconfig/worker_extension.go
- service/controller/v5/version_bundle.go
- vendor/github.com/spf13/cobra/cobra/cmd/license_agpl.go
- vendor/github.com/spf13/cobra/cobra/cmd/license_apache_2.go
- vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_2.go
- vendor/github.com/spf13/cobra/cobra/cmd/license_bsd_clause_3.go
- vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_2.go
- vendor/github.com/spf13/cobra/cobra/cmd/license_gpl_3.go
- vendor/github.com/spf13/cobra/cobra/cmd/license_lgpl.go
- vendor/github.com/spf13/cobra/cobra/cmd/license_mit.go
- vendor/github.com/spf13/cobra/cobra/cmd/licenses.go
Use latest 3.6.2 k8scc in WIP release and align changelog
> Use k8scc 3.6.2 for WIP release

- service/collector/set.go
Some copy paste issue from AWS.
> fixes godoc

- service/controller/v3/resource/deployment/resource.go
- service/controller/v3patch1/resource/deployment/resource.go
- service/controller/v4/resource/deployment/resource.go
- service/controller/v5/resource/deployment/resource.go
Towards https://github.com/giantswarm/giantswarm/issues/4363.
> fixes deployment updates when deployments got deleted in the azure console

- service/controller/v5/resource/instance/create.go
- service/controller/v5/resource/instance/status.go
Just some boyscouting. In the next PR I want to address some improvements for the status management.
> moves status magic to separate files

- service/controller/v5/key/error.go
- service/controller/v5/key/key.go
- service/controller/v5/resource/instance/create.go
- service/controller/v5/resource/instance/create_test.go
Closes https://github.com/giantswarm/giantswarm/issues/4674.
> removes panic and adds more proper error handling

- service/controller/v3/resource/service/current.go
- service/controller/v3patch1/resource/service/current.go
- service/controller/v4/resource/service/current.go
- service/controller/v5/resource/service/current.go
Towards https://github.com/giantswarm/giantswarm/issues/4604.
> deletes k8s service when cluster is being deleted

- README.md
By default it's only one year.
> update readme service principal command

- examples/azure-resource-lab-chart/templates/cluster.yaml
- helm/azure-operator-resource-chart/templates/cluster.yaml
Towards https://github.com/giantswarm/giantswarm/issues/2383.
> removes calico domain configuration

- service/controller/v5/resource/vpn/resource.go
Towards: https://github.com/giantswarm/azure-operator/issues/311
Add getter for Azure deployments and networks SDK clients.
> add getter for deployment and network clients

- service/controller/v5/resource/vpn/create.go
- service/controller/v5/resource/vpn/error.go
Towards: https://github.com/giantswarm/azure-operator/issues/311
Add logic to create the VPN gateway.
> vpn create

- Gopkg.lock
- Gopkg.toml
- integration/setup/common.go
- integration/setup/provider.go
- integration/setup/setup.go
- vendor/github.com/giantswarm/e2e-harness/pkg/framework/guest.go
- vendor/github.com/giantswarm/e2etests/clusterstate/clusterstate.go
- vendor/github.com/giantswarm/e2etests/scaling/provider/aws.go
- vendor/github.com/giantswarm/e2etests/scaling/provider/azure.go
- vendor/github.com/giantswarm/e2etests/scaling/provider/kvm.go
- vendor/github.com/giantswarm/e2etests/scaling/provider/spec.go
- vendor/github.com/giantswarm/e2etests/scaling/scaling.go
Towards: https://github.com/giantswarm/giantswarm/issues/4692
> Nodes ready

- vendor/github.com/giantswarm/backoff/backoff.go
related: https://github.com/giantswarm/giantswarm/issues/4113
> Remove nodename_file_optional from calico configmap

- service/collector/deployment.go
- service/collector/set.go
- service/service.go
Fixes https://github.com/giantswarm/giantswarm/issues/4601.
We think dupes are result of extra events during watch phase. See https://github.com/giantswarm/azure-operator/pull/429#issuecomment-454062640 for details.
> collector: list CRs instead of watching them

- service/controller/v4patch1/resource/instance/create.go
- service/controller/v5/resource/instance/create.go
- service/controller/v5/version_bundle.go
integrating changes https://github.com/giantswarm/node-operator/pull/83
towards https://github.com/giantswarm/giantswarm/issues/4942
> integrate node-operator v2

- helm/azure-operator-chart/templates/rbac.yaml
- service/controller/v5/key/key.go
- service/controller/v5/resource/encryptionkey/create.go
- service/controller/v5/resource/encryptionkey/delete.go
- service/controller/v5/resource/encryptionkey/error.go
- service/controller/v5/resource/encryptionkey/resource.go
- service/controller/v5/resource_set.go
Store encryption key and initial vector, used in certificate encryption here https://github.com/giantswarm/azure-operator/pull/464
> Add secret for storing certs key/iv

- service/controller/v5/cloudconfig/template.go
- service/controller/v6/cloudconfig/template.go
- service/controller/v6/version_bundle.go
towards https://github.com/giantswarm/giantswarm/issues/5480
> fix-azure-ingress-loadbalancer

- client/azure_client_set.go
- flag/service/azure/azure.go
- helm/azure-operator-chart/templates/configmap.yaml
- main.go
- service/collector/client.go
- service/collector/deployment.go
- service/collector/set.go
- service/controller/setting/types.go
- service/controller/v4patch1/cloudconfig/template.go
- service/controller/v4patch1/cloudconfig/types.go
- service/controller/v4patch1/resource_set.go
- service/controller/v4patch2/cloudconfig/template.go
- service/controller/v4patch2/cloudconfig/types.go
- service/controller/v4patch2/resource_set.go
- service/controller/v5/cloudconfig/template.go
- service/controller/v5/cloudconfig/types.go
- service/controller/v5/resource_set.go
- service/controller/v6/cloudconfig/template.go
- service/controller/v6/cloudconfig/types.go
- service/controller/v6/resource_set.go
- service/service.go
Fixes https://github.com/giantswarm/giantswarm/issues/4124.
> rename Cloud to EnvironmentName

- service/controller/v6/cloudconfig/master_extension.go
- service/controller/v6/cloudconfig/render.go
- service/controller/v6/cloudconfig/render_test.go
- service/controller/v6/cloudconfig/types.go
- service/controller/v6/cloudconfig/worker_extension.go
- service/controller/v6/resource/instance/deployment.go
- service/controller/v6/resource/instance/types.go
- service/controller/v6/templates/ignition/small.go
Towards https://github.com/giantswarm/giantswarm/issues/4974
> Move format filesystems into ignition

- integration/test/clusterstate/azure.go
- integration/test/clusterstate/error.go
- integration/test/clusterstate/main_test.go
See https://github.com/giantswarm/e2etests/pull/34.
> move clusterstate e2e provider implementation

- integration/test/scaling/error.go
- integration/test/scaling/main_test.go
- integration/test/scaling/provider.go
- integration/test/scaling/spec.go
See https://github.com/giantswarm/e2etests/pull/35.
> move scaling e2e provider implementation

- integration/test/update/error.go
- integration/test/update/label.go
- integration/test/update/label_test.go
- integration/test/update/main_test.go
- integration/test/update/provider.go
See https://github.com/giantswarm/e2etests/pull/36.
> move update e2e provider implementation

- service/controller/v7/cloudconfig/master_template.go
- service/controller/v7/templates/ignition/docker_mount_unit.go
- service/controller/v7/templates/ignition/etcd_mount_unit.go
fix mount units with new ignition
> fix-mount-units

- service/controller/v7/version_bundle.go
Towards https://github.com/giantswarm/giantswarm/issues/5744.
> v7: update changelog

- service/controller/v8/templates/ignition/default_storage_class.go
Add Azure File Storage Classes by default in our clusters.
> Add azure file storage classes

- service/controller/v8/resource/instance/types.go
- service/controller/v8/version_bundle.go
- service/controller/v9/resource/instance/types.go
- service/controller/v9/version_bundle.go
Including some more CVE's and so on.
> Bump coreOs version again before release

- service/collector/set.go
- service/collector/usage.go
Towards https://github.com/giantswarm/giantswarm/issues/5826. Idea here is to have metrics for currently used resources and their limits. Then we can have alerts for certain thresholds.
> add usage collector

- service/controller/v8/version_bundle.go
v8 is not released yet - putting on the finishing touches.
> Shorten release notes to only include link

- service/controller/v9/cloudconfig/master_template.go
- service/controller/v9/cloudconfig/worker_template.go
- service/controller/v9/templates/ignition/vnic_configuration_unit.go
- service/controller/v9/version_bundle.go
Fixing network performance issues
> Increase eth0 tx queue size

- Gopkg.lock
- Gopkg.toml
- vendor/github.com/giantswarm/k8scloudconfig/CHANGELOG.md
- vendor/github.com/giantswarm/k8scloudconfig/v_4_2_0/files/conf/wait-for-domains
- vendor/github.com/giantswarm/k8scloudconfig/v_4_2_0/master_template.go
- vendor/github.com/giantswarm/k8scloudconfig/v_4_3_0/files/conf/wait-for-domains
- vendor/github.com/giantswarm/k8scloudconfig/v_4_3_0/master_template.go
- vendor/github.com/giantswarm/k8scloudconfig/v_4_4_0/files/conf/wait-for-domains
- vendor/github.com/giantswarm/k8scloudconfig/v_4_4_0/master_template.go
- vendor/github.com/giantswarm/k8scloudconfig/v_4_5_0/files/conf/wait-for-domains
- vendor/github.com/giantswarm/k8scloudconfig/v_4_5_0/master_template.go
- vendor/github.com/giantswarm/k8scloudconfig/v_4_6_0/cloudconfig.go
- vendor/github.com/giantswarm/k8scloudconfig/v_4_6_0/files/conf/wait-for-domains
- vendor/github.com/giantswarm/k8scloudconfig/v_4_6_0/master_template.go
- vendor/github.com/giantswarm/k8scloudconfig/v_4_6_0/types.go
- vendor/github.com/giantswarm/k8scloudconfig/v_4_6_0/worker_template.go
Towards giantswarm/giantswarm#6367
Updated k8scloudconfig with kubelet image pull progress deadline. We continue to use the default 1 minute.
> vendor: updated k8scloudconfig

- Gopkg.lock
- service/controller/v9/version_bundle.go
- vendor/github.com/giantswarm/k8scloudconfig/CHANGELOG.md
- vendor/github.com/giantswarm/k8scloudconfig/v_4_6_0/files/config/kubelet-master.yaml.tmpl
- vendor/github.com/giantswarm/k8scloudconfig/v_4_6_0/files/config/kubelet-worker.yaml.tmpl
- vendor/github.com/giantswarm/k8scloudconfig/v_4_6_0/master_template.go
- vendor/github.com/giantswarm/k8scloudconfig/v_4_6_0/worker_template.go
Towards https://github.com/giantswarm/giantswarm/issues/6270
> Vendor cgroup management and resources reservation

- service/controller/cluster.go
- service/controller/v8patch1/version_bundle.go
- service/version_bundles.go
Merge after https://github.com/giantswarm/azure-operator/pull/552
> v8patch1: versionbundle

- service/controller/v9/resource/deployment/template/virtual_network_setup.json
- service/controller/v9/version_bundle.go
add vnet service endpoint for storage
> add-vnet-service-endpoint

- Gopkg.lock
- integration/setup/provider.go
- vendor/github.com/giantswarm/e2etemplates/pkg/chartvalues/aws_operator.go
- vendor/github.com/giantswarm/e2etemplates/pkg/chartvalues/aws_operator_template.go
- vendor/github.com/giantswarm/e2etemplates/pkg/chartvalues/azure_operator.go
- vendor/github.com/giantswarm/e2etemplates/pkg/chartvalues/azure_operator_template.go
- vendor/github.com/giantswarm/e2etemplates/pkg/chartvalues/credentiald.go
- vendor/github.com/giantswarm/e2etemplates/pkg/chartvalues/credentiald_template.go
Towards https://github.com/giantswarm/giantswarm/issues/6736.
> integration: install credential-default Secret during setup

- service/controller/v10/version_bundle.go
- service/controller/v11/version_bundle.go
The bundles have been swapped by mistake
> Fix bundles

- service/controller/cluster.go
- service/controller/v10patch1/version_bundle.go
- service/version_bundles.go
towards https://github.com/giantswarm/giantswarm/issues/6102
> v10patch1: wiring

- service/controller/v10patch1/resource/deployment/template/virtual_network_setup.json
- service/controller/v10patch1/version_bundle.go
towards giantswarm/giantswarm#6102
> Add service endpoints to v10patch1

- Gopkg.lock
- vendor/github.com/giantswarm/k8scloudconfig/v_4_9_0/files/k8s-resource/calico-all.yaml
- vendor/github.com/giantswarm/versionbundle/bundle.go
- vendor/github.com/giantswarm/versionbundle/changelog.go
- vendor/github.com/giantswarm/versionbundle/component.go
- vendor/github.com/giantswarm/versionbundle/release.go
towards giantswarm/giantswarm#6775
> Update versionbundle to include URLs

- Gopkg.lock
- service/controller/v12/resource/instance/create.go
- service/controller/v12/resource/instance/create_test.go
- service/controller/v12/resource/instance/workingset.go
- vendor/github.com/giantswarm/errors/tenant/error.go
- vendor/github.com/giantswarm/statusresource/Gopkg.lock
I discovered a missing nil-check in the code that caused a panic for new clusters.
Fixed just that.
> Fixed nil pointer error

- Gopkg.lock
- Gopkg.toml
- integration/setup/config.go
- vendor/github.com/giantswarm/e2e-harness/pkg/framework/guest.go
Towards https://github.com/giantswarm/giantswarm/issues/4606
See https://github.com/giantswarm/aws-operator/pull/2082#issue-346281926. Adding here so https://github.com/giantswarm/aws-operator/pull/2082#issue-346281926 can be merged.
> Add host k8s client to guest framework for compatibility with e2e-harness

- service/controller/v12/resource/instance/deployment.go
- service/controller/v12/resource/instance/template/main.json
- service/controller/v12/resource/instance/types.go
I performed a little refactoring to make the code easier to understand in my opinion.
> Refactor instance deployment

- Gopkg.lock
- vendor/github.com/giantswarm/operatorkit/controller/collector/error.go
- vendor/github.com/giantswarm/operatorkit/controller/collector/set.go
- vendor/github.com/giantswarm/operatorkit/controller/collector/timestamp.go
- vendor/github.com/giantswarm/operatorkit/controller/controller.go
- vendor/github.com/giantswarm/operatorkit/controller/metric.go
- vendor/sigs.k8s.io/controller-runtime/pkg/builder/controller.go
- vendor/sigs.k8s.io/controller-runtime/pkg/builder/doc.go
- vendor/sigs.k8s.io/controller-runtime/pkg/builder/webhook.go
- vendor/sigs.k8s.io/controller-runtime/pkg/conversion/conversion.go
- vendor/sigs.k8s.io/controller-runtime/pkg/webhook/conversion/conversion.go
- vendor/sigs.k8s.io/controller-runtime/pkg/webhook/conversion/decoder.go
Towards: https://github.com/giantswarm/giantswarm/issues/8548
This fixes the problem with `CRNotDeleted` alert firing falsely analogue to this PR: https://github.com/giantswarm/chart-operator/pull/348
> update operatorkit vendor deps

- .circleci/config.yml
Documented step names as suggested in https://github.com/giantswarm/fmt/pull/92
> Added CircleCI step names

- service/controller/v14/resource/instance/create.go
- service/controller/v14/resource/instance/create_deployment_completed.go
- service/controller/v14/resource/instance/create_deployment_initialized.go
- service/controller/v14/resource/instance/create_deployment_uninitialized.go
- service/controller/v14/resource/instance/create_terminate_old_workers.go
- service/controller/v14/resource/instance/internal/state/funcs.go
- service/controller/v14/resource/instance/internal/state/funcs_test.go
- service/controller/v14/resource/instance/status.go
The initial state is the empty state, so we don't have to check if there is a state defined.
Also, every time we were returning the empty string as a state we use the constant.
> Initial stage for state machine is the empty state

- .gitignore
- helm/azure-operator/Chart.yaml
- helm/azure-operator/templates/configmap.yaml
- helm/azure-operator/templates/deployment.yaml
- helm/azure-operator/templates/psp.yaml
- helm/azure-operator/templates/pull-secret.yml
- helm/azure-operator/templates/rbac.yaml
- helm/azure-operator/templates/secret.yaml
- helm/azure-operator/templates/service-account.yaml
- helm/azure-operator/templates/service.yaml
- helm/azure-operator/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/7819
> flattening: Support versioning in chart

- .circleci/config.yml
Towards https://github.com/giantswarm/giantswarm/issues/7819
> flattening: Release operator on new tag

- .circleci/config.yml
- README.md
- helm/azure-operator-chart/templates/deployment.yaml
- helm/azure-operator-chart/templates/service.yaml
Towards https://github.com/giantswarm/giantswarm/issues/7819
> Fix thiccc deployment

- pkg/project/project.go
- Update Azure SDK client and Service API endpoints https://github.com/giantswarm/azure-operator/pull/692
- Upgrade to Kubernetes `v1.16.7` https://github.com/giantswarm/azure-operator/pull/694
- Skip instances upgrade path during cluster creation https://github.com/giantswarm/azure-operator/pull/679
> Release 3.0.0

- service/collector/set.go
- service/collector/vmss_rate_limit.go
Added a new exporter for the number of available calls we can make to the VMSS list VMs endpoint.
> Vmss rate limit

- service/collector/set.go
- service/collector/vmss_rate_limit.go
Backported the VMSS rate limit exporter to the thiccc branch
> Backported the vmss rate limit exporter to thiccc

- service/collector/set.go
Disabled the resource group exporter which is apparently braking the scraping
> Disabled broken exporter

- Gopkg.lock
- Gopkg.toml
- vendor/github.com/giantswarm/microendpoint/service/version/metric.go
- vendor/github.com/giantswarm/micrologger/CHANGELOG.md
- vendor/github.com/giantswarm/micrologger/Gopkg.lock
- vendor/github.com/giantswarm/micrologger/Gopkg.toml
Towards https://github.com/giantswarm/giantswarm/issues/8636 and https://github.com/giantswarm/giantswarm/issues/7391
> Cleanup reconciled version by updating microendpoint

- service/collector/set.go
- service/collector/vmss_rate_limit.go
Fixes https://github.com/giantswarm/giantswarm/issues/9298
> Already checked subscriptions should not be used again

- service/collector/client.go
Backporting https://github.com/giantswarm/azure-operator/pull/713
> Avoid collecting metrics twice

- service/collector/vmss_rate_limit.go
Backporting of the modification from the thiccc branch
> meaningful values for api rate metrics even when 429 error is firing

- service/controller/resource/instance/instance_update_watchdog.go
See https://gigantic.slack.com/archives/CNUDS3AMU/p1585661137167700
> fixed placeholders

- service/controller/v13/resource/instance/create_deployment_completed.go
get location from resource group instead of from deployment
> get location from resource group

- service/controller/v13/key/key.go
- service/controller/v13/resource/instance/create_deployment_completed.go
- service/controller/v13/resource/instance/create_deployment_uninitialized.go
- service/controller/v13/resource/instance/deployment.go
- service/controller/v13/resource/instance/resource.go
Handle germanywestcentral (no availability zones)
> Thiccc az gwc

- pkg/httputil/error.go
- pkg/httputil/parser.go
- pkg/httputil/parser_test.go
Towards https://github.com/giantswarm/giantswarm/issues/9912
> Add parser function for HTTP Retry-After

- service/controller/resource/instance/deployment.go
- service/controller/resource/instance/template/main.json
- service/controller/resource/instance/template/vmss.json
to force an upgrade even when the arm template is not changed.
> add azure operator version to ARM parameters

- pkg/project/project.go
Bump to new dev/prerelease version.
> Bump to v3.0.6-dev

- service/controller/resource/deployment/checksum.go
- service/controller/resource/deployment/error.go
- service/controller/resource/deployment/resource.go
- service/controller/resource_set.go
Towards https://github.com/giantswarm/giantswarm/issues/9862
> Cancel full reconciliation if ARM deployment for deployment resource has not finished

- helm/azure-operator/templates/deployment.yaml
Follow up to remove $. As per the docs https://helm.sh/docs/chart_template_guide/builtin_objects
Will go with a ping.
> Fix Release.Revision templating

- pkg/checksum/checksum.go
- pkg/checksum/checksum_test.go
- pkg/checksum/error.go
- pkg/helpers/vmss/types.go
- service/controller/key/key.go
- service/controller/resource/instance/create_deployment_completed.go
- service/controller/resource/instance/create_deployment_initialized.go
- service/controller/resource/instance/create_deployment_uninitialized.go
- service/controller/resource/instance/create_provisioning_successful.go
- service/controller/resource/instance/deployment.go
- service/controller/resource/instance/error.go
- service/controller/resource/instance/status.go
Towards: https://github.com/giantswarm/giantswarm/issues/10055
Moved the checksum feature to a common package to allow reuse.
Moved some type definitions to a common helper package to allow reuse.
> Moved stuff to common package

- service/controller/resource/masters/create.go
- service/controller/resource/masters/create_deployment_uninitialized.go
- service/controller/resource/masters/deployment.go
- service/controller/resource/masters/error.go
- service/controller/resource/masters/resource.go
Towards https://github.com/giantswarm/giantswarm/issues/10055
This PR implements the first state transition handler for the new `masters` resource.
Mostly copy-paste from the `instance` resource implementation.
> Added implementation of the first state for the new masters resource

- service/controller/resource/masters/create.go
- service/controller/resource/masters/create_cluster_upgrade_requirement_check.go
- service/controller/resource/masters/create_deployment_initialized.go
- service/controller/resource/masters/create_provisioning_successful.go
- service/controller/resource/masters/error.go
Towards: https://github.com/giantswarm/giantswarm/issues/10055
Added imlementation of a few more transition functions for the new `masters` resource.
Mostly copy-paste from the `instance` resource.
> Added implementation to 3 more transition functions

- service/controller/resource/masters/create.go
- service/controller/resource/masters/create_deployment_completed.go
- service/controller/resource/masters/create_wait_for_masters_to_become_ready.go
Towards: giantswarm/giantswarm#10055
Added imlementation of a few more transition functions for the new masters resource.
Mostly copy-paste from the instance resource.
> Added two more transition functions for the new `masters` resource

- service/controller/resource/masters/create.go
- service/controller/resource/masters/create_master_instances_upgrading.go
- service/controller/resource/masters/resource.go
- service/controller/resource/masters/workingset.go
- service/controller/resource/masters/workingset_test.go
Towards: giantswarm/giantswarm#10055
This the last transition function implementation and the last PR for the whole feature.
Thanks for bearing with me team.
> Added final transition function implementation

- pkg/project/project.go
- service/controller/resource/instance/template/main.json
- service/controller/resource/masters/template/main.json
Added `Standard_E8a_v4` and `Standard_E8as_v4` VM sizes for masters and workers.
> Add Standard_E8a_v4 and Standard_E8as_v4 VM sizes

- CHANGELOG.md
- helm/azure-operator/templates/_resource.tpl
- helm/azure-operator/templates/deployment.yaml
- helm/azure-operator/templates/network-policy.yaml
- helm/azure-operator/values.yaml
towards giantswarm/giantswarm/issues/4383
> Add network policy

- .circleci/config.yml
- CHANGELOG.md
Towards https://github.com/giantswarm/giantswarm/issues/10423.
> Update architect-orb to 0.8.14

- service/controller/resource/masters/create_deployment_completed.go
This fixes a loop in cluster upgrade in GWC
> Fix checkcum calculation for GWC region

- CHANGELOG.md
This PR adds changelog entry for changes done in #827
Also fixed formatting/nesting for Fixed entries in the Unreleased changelog
> Add changelog entry for NGINX LB Service move

- go.mod
- service/controller/resource/instance/create_deployment_completed.go
- service/controller/resource/masters/create_block_api_calls.go
- service/controller/resource/masters/create_deployment_completed.go
This PR backport the changes happened on the 4.0.0 branch to the 4.1.0 release branch
> backported changes from patched 4.0.0 releases to 4.1.0 release branch

- CHANGELOG.md
- helm/azure-operator/Chart.yaml
- service/controller/resource/masters/create_block_api_calls.go
Merge 4.0.1 changes to master branch
> Merge 4.0.1 changes to master branch

- .circleci/config.yml
- helm/azure-operator/ci/default-values.yaml
- helm/azure-operator/templates/configmap.yaml
- helm/azure-operator/templates/rbac.yaml
- integration/setup/provider.go
- main.go
I used the CIDR in the installations repository as default.
> Pass IPAM network CIDR as parameter to the operator

- go.mod
- go.sum
- pkg/project/project.go
- service/controller/cloudconfig/master_template.go
- service/controller/cloudconfig/worker_template.go
- service/controller/key/key.go
- service/controller/resource/blobobject/desired.go
After fixing a small bug in worker template in k8scloudconfig, update it to
latest version in master to pull the changes into development branches as well.
> Update k8scloudconfig to latest version

- .circleci/config.yml
Use latest version that includes retries when pushing to catalog.
> Update architect orb

- CHANGELOG.md
- service/controller/internal/vmsscheck/deleter_job.go
- service/controller/internal/vmsscheck/guard_job.go
- service/controller/internal/vmsscheck/instance_watchdog.go
- service/controller/internal/vmsscheck/spec.go
- service/controller/internal/vmsscheck/vmss.go
- service/controller/resource/instance/create_deployment_uninitialized.go
- service/controller/resource/instance/create_scale_workers.go
- service/controller/resource/masters/create_deployment_uninitialized.go
- service/controller/resource/masters/create_master_instances_upgrading.go
I'm using the factory in my nodepools branch, and I need this part to be different. Instead of adding the changes to my PR, I think it's better to fix it on master.
> Make vmss check to use the azure client factory

- pkg/project/project.go
- service/controller/cloudconfig/master_template.go
- service/controller/cloudconfig/types.go
- service/controller/cloudconfig/worker_template.go
- service/controller/resource/blobobject/desired.go
Backporting some fixes done in the 4.2.0 release branch to master
This fix is needed to support k8s 1.17
> Release 4 2 0

- service/controller/cluster.go
- service/controller/resource/deployment/resource.go
Towards https://github.com/giantswarm/giantswarm/issues/12024
> Use azure clients factory

- client/azure_client_set.go
- client/factory.go
Towards https://github.com/giantswarm/giantswarm/issues/12024
> Added subnet clients to client factory

- CHANGELOG.md
> Added changelog for docker registry mirrors

- go.mod
- go.sum
- service/controller/key/key.go
BUmped k8scloudconfig to 7.0.1
> Bump k8scc

- docs/running_e2etests_locally.md
- integration/README.md
Towards https://github.com/giantswarm/giantswarm/issues/12063
> Remove pull secret references

- CHANGELOG.md
- helm/azure-operator/templates/configmap.yaml
Towards https://github.com/giantswarm/giantswarm/issues/12063
> Use fixed value for registry domain & mirrors

- .circleci/config.yml
Let's trigger e2e tests manually for now
> remove filter from hold for e2e

- service/controller/resource/cloudconfig/resource.go
Towards https://github.com/giantswarm/giantswarm/issues/12063
> Fix setting azureClientsFactory in cloudconfig resource

- Dockerfile
- pkg/project/project.go
Towards https://github.com/giantswarm/giantswarm/issues/12063
> Fix copying k8scloudconfig files in Dockerfile

- .circleci/config.yml
`release-operator` does the job now!
> No longer push to app collection

- CHANGELOG.md
- pkg/project/project.go
- service/controller/resource/deployment/resource.go
Towards: https://github.com/giantswarm/giantswarm/issues/12501
This PR changes the behaviour of the `deployment` resource.
It will apply the ARM deployment regardless of the checksum being changed when the main ARM template is in a failed state.
> Retry failed deploy

- go.mod
- integration/test/crmapping/crmapping_test.go
- integration/test/crmapping/error.go
- integration/test/crmapping/testdata/simple_azureconfig.yaml
This change provides initial structure to introduce CR mapping integration test
for AzureConfig to CAPI CRs functionality.
> Add initial structure for CR mapping integration test

- service/controller/resource/clusterdependents/resource.go
- service/controller/resource/machinepooldependents/resource.go
When Cluster CR gets deleted, we must also ensure that all child CRs for the
given cluster are deleted. The sequence of events is as follows:
Delete Cluster
-> Delete AzureCluster
-> Delete MachinePools
-> Delete AzureMachinePools
-> Delete Spark CR
-> Delete Secret
> Ensure cluster child CRs are deleted on delete

- pkg/project/project.go
I always fuck this up in PRs...
> Put pkg/project/project.go version straight

- client/azure_client_set.go
- client/factory.go
This PR migrates azure's DNSRecordsClient and interfaceClient to the new factory system
> Added azure clients

- go.mod
- go.sum
- pkg/project/project.go
- service/controller/azure_config.go
- service/controller/cloudconfig/master_template.go
- service/controller/resource/blobobject/desired.go
- service/controller/resource/blobobject/resource.go
- service/controller/resource/blobobject/update_test.go
- service/controller/resource/subnet/resource.go
Towards https://github.com/giantswarm/giantswarm/issues/12093
> Use annotations to configure masters OIDC

- .circleci/config.yml
- e2e/test/scaling/error.go
- e2e/test/scaling/provider.go
This PR fixes the scaling e2e test that was broken
4 tests are failing because I didn't run them.
> Fix scaling error

- service/controller/cloudconfig/cloud_config.go
- service/controller/cloudconfig/error.go
- service/controller/cloudconfig/types.go
I didn't want to block the testing, that's why I didn't add these changes in the previous PR. This PR simplifies the code that we copied from randomkeys. I don't think most of it was necessary.
> Simplify how we find encryption secret

- client/azure_client_set.go
These clients were missing for some reason. Going with a ping.
> Wire clients in azure client set

- client/azure_client_set.go
- client/factory.go
- client/organization_factory.go
- go.sum
- pkg/project/project.go
- service/controller/azure_machine_pool.go
- service/controller/internal/vmsku/error.go
- service/controller/internal/vmsku/vmsku.go
- service/controller/key/key.go
- service/controller/resource/nodepool/deployment.go
- service/controller/resource/nodepool/error.go
- service/controller/resource/nodepool/resource.go
- service/service.go
This PR aims at enabling the AcceleratedNetworking feature when the CAPZ flag is set to nil, only when the instance type supports it.
> Accelerated networking nil

- go.mod
- go.sum
this PR bumps operatorkit to latest patch to solve a problem in cluster deletion
> bumped operatorkit

- CHANGELOG.md
- service/controller/internal/vmsscheck/error.go
- service/controller/internal/vmsscheck/vmss.go
- service/controller/resource/nodepool/create_scale_workers.go
Towards: https://github.com/giantswarm/giantswarm/issues/13950
This PR removes the 50% VMSS API calls security check
> Removed 50% VMSS calls remaining check

- pkg/project/project.go
Reverting project version in master :)
> Revert project version

- CHANGELOG.md
- pkg/project/project.go
- service/controller/resource/capzcrs/create.go
- service/controller/resource/capzcrs/testdata/azurecluster_with_partial_vnet.yaml
- service/controller/resource/capzcrs/testdata/azurecluster_with_subnets.yaml
- service/controller/resource/capzcrs/testdata/case-0-Simple-AzureConfig-migration-to-create-CAPI-CAPZ-CRs_AzureCluster.golden
- service/controller/resource/capzcrs/testdata/case-1-Simple-AzureConfig-reconciliation-to-verify-existing-CAPI-CAPZ-CRs_AzureCluster.golden
- service/controller/resource/capzcrs/testdata/case-2-Modified-AzureConfig-reconciliation-to-update-existing-CAPI-CAPZ-CRs_AzureCluster.golden
- service/controller/resource/capzcrs/testdata/case-3-Ensure-that-AzureCluster-Subnets-are-not-wiped_AzureCluster.golden
- service/controller/resource/capzcrs/testdata/case-4-Ensure-that-AzureCluster-VNET-gets-updated_AzureCluster.golden
- service/controller/resource/capzcrs/testdata/case-5-Ensure-that-AzureCluster-partial-VNET-gets-updated_AzureCluster.golden
- service/controller/resource/capzcrs/testdata/simple_azurecluster.yaml
- service/controller/resource/ipam/azure_machinepool_network_range_getter.go
- service/controller/resource/ipam/azure_machinepool_subnet_collector.go
- service/controller/resource/ipam/azure_machinepool_subnet_persister.go
- service/controller/resource/spark/create.go
- service/controller/resource/spark/error.go
- service/controller/resource/subnet/resource.go
Towards https://github.com/giantswarm/giantswarm/issues/14111
> Stop using deprecated field

- service/controller/resource/capzcrs/create.go
- service/controller/resource/capzcrs/testdata/case-0-Simple-AzureConfig-migration-to-create-CAPI-CAPZ-CRs_Cluster.golden
Cluster CR has service domain as a field. Use correct value for that.
> Use correct value for cluster service domain

- helm/azure-operator/templates/secret.yaml
Towards https://github.com/giantswarm/giantswarm/issues/14650
> Define secret as an included template

- service/controller/azure_machine_pool.go
- service/controller/resource/nodepool/resource.go
This fixes nodepool handler creation, which should fix the panic discovered during latest upgrade testing.
> Fix nodepool handler creation

- service/controller/resource/azureconfig/create.go
- service/controller/resource/machinepoolupgrade/lastdeployedreleaseversion.go
Towards https://github.com/giantswarm/giantswarm/issues/15156, more fixes similar to https://github.com/giantswarm/azure-operator/pull/1258
What's in the box:
- Fixes issue where API conflict error happens in `azureconfig` handler when updating `AzureConfig` CR.
- Fixes issue where API conflict error happens in `machinepoolupgrade` handler when updating `MachinePool` CR.
> Fix catching more k8s API conflict errors

- pkg/handler/ipam/azure_machinepool_subnet_releaser.go
> Fix debugf logging

- CHANGELOG.md
- pkg/tenantcluster/error.go
- service/controller/machinepool/handler/nodestatus/create.go
Fixes https://github.com/giantswarm/giantswarm/issues/15385
> Handle WC API not available error in nodestatus

- CHANGELOG.md
- pkg/handler/ipam/azure_machinepool_subnet_persister.go
- pkg/handler/ipam/azure_machinepool_subnet_releaser.go
- service/controller/azurecluster/handler/azureclusterconditions/create.go
- service/controller/azurecluster/handler/azureclusterupgrade/resource.go
- service/controller/azurecluster/handler/azureconfig/create.go
- service/controller/azurecluster/handler/subnet/resource.go
- service/controller/azuremachine/handler/azuremachineconditions/create.go
- service/controller/azuremachinepool/handler/azuremachinepoolconditions/create.go
- service/controller/azuremachinepool/handler/nodepool/create.go
- service/controller/azuremachinepool/handler/nodepool/create_deployment_uninitialized.go
- service/controller/cluster/handler/clusterupgrade/create.go
- service/controller/machinepool/handler/machinepoolownerreference/resource.go
- service/controller/machinepool/handler/machinepoolupgrade/lastdeployedreleaseversion.go
- service/controller/machinepool/handler/machinepoolupgrade/resource.go
- service/controller/machinepool/handler/nodestatus/create.go
Towards https://github.com/giantswarm/giantswarm/issues/15203
> Don't use 'stack' with Debugf

- go.mod
- go.sum
- service/controller/azuremachinepool/handler/azuremachinepoolconditions/create.go
Towards: https://github.com/giantswarm/giantswarm/issues/15471
Bumped capz dependency and removed workaround after bug was fixed upstream
> removed workaround

- helm/azure-operator/templates/rbac.yaml
forgot to add azureclusteridentity to clusterrole
> fixed rbac for azureclusteridentity feature

- service/controller/azuremachine/handler/azuremachinemetadata/create.go
Fixing https://github.com/giantswarm/azure-operator/pull/1367/files#r579018913
> Don't use stack with debugf

- CHANGELOG.md
- service/controller/azureconfig/handler/masters/create_cluster_upgrade_requirement_check.go
- service/controller/azureconfig/handler/masters/create_deployment_completed.go
- service/controller/azureconfig/handler/masters/create_master_instances_upgrading.go
- service/controller/unhealthynode/handler/terminateunhealthynode/create.go
Towards https://github.com/giantswarm/giantswarm/issues/15732
> Don't error when workload cluster is not ready yet

- helm/azure-operator/Chart.yaml
Towards giantswarm/giantswarm#14846
> Add team annotation to Chart.yaml

- helm/azure-operator/Chart.yaml
- helm/azure-operator/ci/default-values.yaml
- helm/azure-operator/templates/configmap.yaml
- helm/azure-operator/templates/secret.yaml
Towards https://github.com/giantswarm/giantswarm/issues/16587
`giantswarm/config`: https://github.com/giantswarm/config/pull/37
> use giantswarm config

- go.mod
- go.sum
> bump jwt-go

- CHANGELOG.md
- go.mod
- go.sum
> Bumped k8scc

- CHANGELOG.md
- go.mod
- go.sum
This release of k8scloudconfig includes a change to better detect memory eviction thresholds.
> Upgrade k8scloudconfig to v10.8.1

- helm/azure-operator/Chart.yaml
Towards https://github.com/giantswarm/giantswarm/issues/19760
> Set team annotation in Chart.yaml for app alert routing

- CHANGELOG.md
- service/controller/azureconfig/handler/deployment/template/main.json
- service/controller/azuremachinepool/handler/nodepool/template/parameters.go
- Fix a panic in groups version param check
- Add GiantSwarmCluster tag to VirtualNetwork
> Cgroup panic

- CHANGELOG.md
- integration/test/crmapping/crmapping_test.go
- service/controller/azurecluster/controller.go
- service/controller/azurecluster/handler/azureconfig/create.go
- service/controller/azurecluster/handler/azureconfig/error.go
- service/controller/azurecluster/handler/azureconfig/resource.go
This PR allows customers to specify the cluster CIDR in the `AzureCluster` CR.
> Added possibility to specify VNet CIDR in `AzureCluster`.

- CHANGELOG.md
- go.mod
- go.sum
Bump k8scc to fix syntax error in k8scc
> K8s addons fix

- .nancy-ignore
- renovate.json
I want to test [these changes](https://github.com/giantswarm/devctl/pull/449/files).
> Constraint renovate updates to 1.18

- CHANGELOG.md
- go.mod
- go.sum
Towards: https://github.com/giantswarm/roadmap/issues/1895
> Cronjob feature gate

- CHANGELOG.md
- helm/azure-operator/values.schema.json
fix helm schema that was preventing app to be installed
> Fix helm values json schema.

- helm/azure-operator/templates/pss-exceptions.yaml
Fix PolicyException by adding ReplicaSet subresource.
> Fix PolicyException
