giantswarm/azure-operator

.gitignore, Dockerfile, examples/cluster.yaml, examples/local/README.md, examples/local/cluster.tmpl.yaml, examples/local/configmap.tmpl.yaml, examples/local/deployment.tmpl.yaml
Towards giantswarm/giantswarm#1707
This PR adds a local setup guide as well as the Dockerfile and an example TPO. The local setup doesn't cover certs yet because we don't need them till we're ready to boot machines.
=> Local setup guide

service/arm_templates/cluster_setup.json
Towards #7 
A first version of the Cluster Setup template. For now, it just creates the Storage Account and outputs the name.
The storage account name is very restrictive (3-24 chars only lowercase alphanumeric). So the uniquestring function is used to generate it. The storage account is tagged with the clusterID so we can query for it.
See https://docs.microsoft.com/en-us/azure/architecture/best-practices/naming-conventions
=> Add Cluster Setup ARM template.

service/key/key.go, service/key/key_test.go, service/operator/service.go, service/service.go
Towards #5 
This PR adds the operatorkit reconciler framework and uses it in the addFunc and deleteFunc. The resources collection is currently empty. I'll add the ResourceGroup resource in a later PR.
This PR also adds the key service for retrieving values from the cluster TPO.
=> Add reconciler framework and key service

service/arm_templates/cluster_setup.json, service/arm_templates/main.json, service/arm_templates/security_groups_setup.json, service/arm_templates/virtual_network_setup.json
It is now possible to call the template main.json to deploy the cluster_setup.json, security_groups_setup.json and virtual_network_setup.json templates.
If you want to test it with the azure-cli, you'll only have to provide the clusterID, masterLoadBalancerCidr and workerLoadBalancerCidr parameters since they don't have defaults. If you have an idea of what a good default address could be for the 2 loadbalancers, let me know.
I also tried matching the templates' parameters to the azuretpr [structures elements](https://github.com/giantswarm/azuretpr/tree/39b23dfc8bebc3a706b3b8dd286a3612e0fe35b2/spec/azure). 
I think an important part to review is the [parameters block](https://github.com/giantswarm/azure-operator/pull/16/files#diff-bdfeb20a499ae8d7abc02b96a7ec37a5R4) in the main template …
=> Main arm template

service/cloudconfig/template.go
Fixes a problem with the `get-keyvault-secrets.service` it should be called `/opt/bin/get-keyvault-secrets` to match the unit. Thanks for spotting this @Cocotton!
=> Fix script name for get secrets unit

service/arm_templates/certificates.json, service/arm_templates/main.json, service/arm_templates/node_setup.json
Since we can't get the VMs Service Principal IDs, from within the ARM template, to populate the Vault AccessPolicies, this PR only makes sure the MSI extensions are available on all nodes.
=> Azure vault access

main.go, service/resource/deployment/resource.go, service/resource/deployment/resource_test.go, service/resource/deployment/template.go
Towards https://github.com/giantswarm/azure-operator/issues/30
Pointing to master was unpredictable as changes may be merged any time.
Now when templates are changed we need to redeploy the operator as well.
=> service: set template URI version to the git SHA

service/service.go
This fixes the operator. Otherwise, it would complain anout the BackOff configuration being empty and would fail.
=> Set a default backoff framework backoff configuration

helm/azure-operator-chart/Chart.yaml, helm/azure-operator-chart/templates/configmap.yaml, helm/azure-operator-chart/templates/deployment.yaml, helm/azure-operator-chart/templates/pull-secret.yml, helm/azure-operator-chart/templates/secret.yaml, helm/azure-operator-chart/templates/service.yaml
Minimal drop required to use in `gollum` Azure host cluster.
Related change: https://github.com/giantswarm/installations/pull/153
=> Adds Helm chart

service/cloudconfig/service.go, service/operator/framework.go, service/operator/service.go, service/resource/deployment/resource_test.go, service/service.go
I think having Viper and Flag spread across packages isn't nice. It's confusing and makes test setup harder. Now only service package has knowledge how to deal with that. It wires dependencies and passes them to the subpackages.
=> service: remove viper dependency in subpackages

service/arm_templates/main.json, service/arm_templates/node_setup.json
This PR adds the parameter `assignContributorRole` to the node_setup.json template.
When passing `true`, to node is assigned the "contributor role" in the resource group.
I added that flag because I was not sure we wanted to give that role to the worker nodes.
Unfortunately, I cannot test this completely because I don't have the permission to give the contributor role to a VM. See the following error
```
The client 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX' with object id 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX' does not have permission to perform action 'Microsoft.Authorization/roleAssignments/write'
```
=> Msi roles assignment

service/arm_templates/node_setup.json
- Fix role assignment. Azure complained about name, because it should be in `guid` format.
- We need additional role for azure-operator account to assign MSI roles. Added section how to create azure-operator service principal and assign additional role.
=> Fix msi rbac

service/resource/deployment/resource.go, service/resource/resourcegroup/resource.go
Number of resources we create is much bigger than in the beginning.
Right now creation/deletion takes often >20m.
Hopefully this decrease after we remove storage account resource.
=> deployment,resourcegroup: increase timeouts to 30m

service/cloudconfig/service.go
This is to enable clean removal in the future. When removing const and
there is still some loopback address left, the code will not compile.
=> cloudconfig: extract loopbackAddr const

client/azure.go, service/resource/dnsrecord/current.go, service/resource/dnsrecord/delete.go, service/resource/dnsrecord/desired.go, service/resource/dnsrecord/resource.go, service/resource/dnsrecord/update.go
`azure-sdk-for-go/arm/dns` is deprecated. This also bumps the API
version.
=> client,dnsrecord: use mgmt/2017-09-01/dns package

service/arm_templates/main.json, service/arm_templates/node_setup.json, service/arm_templates/security_groups_setup.json, service/cloudconfig/template.go, service/key/key.go, service/resource/deployment/deployment.go
- allow ip forwarding
- add security rules to allow pods/calico traffic
- fix ingress load balancer ports
TL;DR allow pods subnet in security groups
For context:
In Azure Calico uses native Azure routing. So pods will (should) use ip range from virtual network range.
For example
virtual network: 10.0.0.0/16
calico/pods network: 10.0.128.0/17 <-  my recommendation to just pick up second half of virt.network range. Every Kubernetes node will pick /24 from this subnet.
=> Network imporovements for Calico

service/cloudconfig/template.go
Tested in `gollum`
Fixes problem with mounts. This sets explicit dependency on `multi-user.target`.
Before unit was started by coreos-cloudinit, not automatically by systemd.
=> Adds [Install] section to mount units

service/key/key.go, service/key/key_test.go
Towards https://github.com/giantswarm/giantswarm/issues/2491
Prefixing KeyVault with cluster ID is risky because of naming
constraints. KeyVault name must not start with a number. The name has to
be globally unique.
I decided to prefix it (and eventually all other resources) with gs- to
guarantee we always start with a letter and avoid such situations in the
future.
Follow up issue https://github.com/giantswarm/giantswarm/issues/2535
=> key: fix KeyVault name

service/cloudconfig/service.go
As this limitation (https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-troubleshoot#cause-3-accessing-the-load-balancer-from-the-same-vm-and-network-interface) is not valid anymore - we can use the same approach for accessing API as in other operators. 
Do we want to remove the possibility of overriding this in k8scloudconfig? E.g. here:
https://github.com/giantswarm/k8scloudconfig/blob/master/v_3_1_1/cloudconfig.go#L39-L44
=> Remove loopback reference to kubernetes API

service/cloudconfig/service.go
There was a race between kubelet and waagent. When certs are passed with
cloudconfigs instead of downloading them from KeyVault, kubelet starts
way faster. /var/lib/waagent/ManagedIdentity-Settings is mounted to the
kubelet container. If waagent doesn't have enough time to write to this
file, docker container with kubelet starts and makes it a directory, and
then waagent fails to write to the file (because it's a directory).
Mounting /var/lib/waagent instead solves the problem
=> cloudconfig: fix waagent race

service/azureconfig/v1/arm_templates/main.json, service/azureconfig/v1/cloudconfig/service.go
Towards https://github.com/giantswarm/giantswarm/issues/2490 https://github.com/giantswarm/giantswarm/issues/2483
On Azure only master nodes use etcd, so it is locked down for
simplification and security.
=> azureconfig/v1: remove etcd DNS

flag/service/installation/installation.go, flag/service/service.go, helm/azure-operator-chart/templates/configmap.yaml, main.go, service/azureconfig/framework.go, service/azureconfig/v1/key/key.go, service/azureconfig/v1/key/key_test.go, service/azureconfig/v1/resource/resourcegroup/resource.go, service/azureconfig/v1/resource/resourcegroup/resource_test.go, service/azureconfig/v1/resource_set.go, service/service.go
Towards giantswarm/giantswarm#2775
Adds the tags below to each Resource Group for cost tracking.
```
GiantSwarmCluster: "rue77"
GiantSwarmOrganization: "giantswarm"
GiantSwarmInstallation: "gollum"
```
Replaces the previous tags.
```
ClusterID: "rue77"
CustomerID: "giantswarm"
```
=> Resource tags

Dockerfile
Uses the latest alpine as discussed with Tim.
https://github.com/giantswarm/e2e-app/pull/3#discussion_r174731859
I'd like us to use the latest version in our operators.
=> Use latest alpine as base image

service/azureconfig/setting/types.go
The error message when `--service.azure.location error message` is empty was incorrectly showing:
```
panic: [{[...]/azureconfig/framework.go:59: azureconfig.FrameworkConfig.Azure.CIDR must not be empty} {invalid config}]
```
I corrected this to show
```
panic: [{[...]/azureconfig/framework.go:59: azureconfig.FrameworkConfig.Azure.Location must not be empty} {invalid config}]
```
=> correct --service.azure.location error message

helm/azure-operator-chart/templates/service.yaml
Noticed this earlier, so with the annotation, we now scrape azure-operator, e.g: `go_memstats_alloc_bytes{app="azure-operator"}` on `godsmack` now gives me:
Element | Value
-- | --
go_memstats_alloc_bytes{app="azure-operator",cluster_id="godsmack",cluster_type="host",instance="10.0.133.26:8000",job="host-cluster-godsmack-workload",namespace="giantswarm"} | 5071384
=> Adds prometheus scrape annotation

service/azureconfig/v1/arm_templates/security_groups_setup.json
Towards https://github.com/giantswarm/giantswarm/issues/2372
Master:
Worker:
and when i submit the namespace, service and endpoint, monitoring targets come up correctly in prometheus bam bam
=> Opens required ports for monitoring

helm/azure-operator-chart/templates/rbac.yaml, service/azureconfig/v1/resource/service/create.go, service/azureconfig/v1/resource/service/create_test.go, service/azureconfig/v1/resource/service/current.go, service/azureconfig/v1/resource/service/delete.go, service/azureconfig/v1/resource/service/delete_test.go, service/azureconfig/v1/resource/service/desired.go, service/azureconfig/v1/resource/service/desired_test.go, service/azureconfig/v1/resource/service/error.go, service/azureconfig/v1/resource/service/resource.go, service/azureconfig/v1/resource/service/update.go, service/azureconfig/v1/resource_set.go
Towards https://github.com/giantswarm/giantswarm/issues/2372
e.g:
```
$ kubectl get -n=heu7i svc master -o yaml
apiVersion: v1
kind: Service
metadata:
annotations:
giantswarm.io/prometheus-cluster: heu7i
creationTimestamp: 2018-04-09T10:36:24Z
labels:
app: master
cluster: heu7i
customer: giantswarm
name: master
namespace: heu7i
resourceVersion: "2921913"
selfLink: /api/v1/namespaces/heu7i/services/master
uid: da1d0187-3be1-11e8-af51-000d3a2870da
spec:
clusterIP: 172.31.0.105
ports:
- port: 443
protocol: TCP
targetPort: 443
sessionAffinity: None
type: ClusterIP
status:
loadBalancer: {}
```
=> Adds service resource

README.md
Message is out of date and doesn't need to link to AWS.
=> Remove under construction message

service/controller/v1/key/key.go, service/controller/v1/resource/endpoints/desired.go, service/controller/v1/resource/endpoints/nic.go
After migration to vmss, the endpoint resource broke because it try to read get the Network Interface Controller using the old method `interfacesClient.Get`.
We now need to retrieve the network interface from the vmss using `interfacesClient.ListVirtualMachineScaleSetNetworkInterfaces`. This PR implement this method.
the encountered error is
```
W 18-04-24 10:40:30 /apis/provider.giantswarm.io/v1alpha1/namespaces/default/azureconfigs/dfi0y retrying due to error | operatorkit/controller/resource/retryresource/crud_resource_ops_wrapper.go:96 | function=GetDesiredState | resource=endpointsv1 | underlyingResource=endpointsv1
/go/src/github.com/giantswarm/azure-operator/vendor/github.com/giantswarm/operatorkit/controller/resource/retryresource/crud_resource_ops_wrapper.go:89: …
```
=> fix: Microsoft.Network/networkInterfaces/<cluster name>-Master-1-NIC not found

service/controller/v1/resource/deployment/resource.go, service/controller/v1/resource/endpoints/current.go, service/controller/v1/resource/service/current.go
They are deleted with the namespace. Endpoints does failing Azure API
calls on deletion so this change is necessary.
=> v1: cancel endpoints & service deletion

Gopkg.lock, vendor/github.com/giantswarm/certs/searcher.go
This update fixes problem with old clusters that don't have
calico-etcd-client certs.
=> Update certs dependency

helm/azure-operator-chart/templates/deployment.yaml
This is needed so that Helm/Kubernetes notices changes on
deployment/configmap and therefore pushes configmap update to helm
bundle.
Towards https://github.com/giantswarm/giantswarm/issues/3022
=> Add configmap checksum to deployment

Gopkg.lock, client/azure.go, flag/service/azure/azure.go, helm/azure-operator-chart/templates/configmap.yaml, integration/template/azure_operator_charts_values.go, main.go, service/controller/setting/types.go, service/controller/v1/resource/deployment/resource_test.go, service/controller/v1/resource/resourcegroup/resource_test.go, service/controller/v1/version_bundle.go, service/controller/v2/cloudconfig/template.go, service/controller/v2/cloudconfig/types.go, service/controller/v2/resource/deployment/resource_test.go, service/controller/v2/resource/resourcegroup/resource_test.go, service/controller/v2/version_bundle.go, service/service.go, vendor/github.com/giantswarm/k8scloudconfig/v_3_3_0/master_template.go
There are multiple changes:
- added new configuration flag `--service.azure.cloud`
- added cloud support to azure client package (made it similar as done in Kubernetes)
- updated calico to 3.0.5 (as it was in changelog, but template was not updated)
- make `v2` active release and deprecate `v1`
Related: https://github.com/giantswarm/installations/pull/310
Related: https://github.com/giantswarm/k8scloudconfig/pull/368
Status: Tested in `tarantula` cluster creation started, but vmss fail to be created with "Internal server error" from Azure. Working on it.
=> Add germancloud support

.circleci/config.yml
There was the hold target introduced in https://github.com/giantswarm/azure-operator/pull/207 but the build names are not aligned. This PR fixes this.
=> fixes build names

.circleci/config.yml, service/controller/v2/cloudconfig/cloud_config.go, service/controller/v2/cloudconfig/master_extension.go, service/controller/v2/cloudconfig/worker_extension.go, service/controller/v2/resource/deployment/network.go, service/controller/v2/resource/deployment/resource.go, service/controller/v2/resource/dnsrecord/create.go, service/controller/v2/resource/dnsrecord/current.go, service/controller/v2/resource/dnsrecord/delete.go, service/controller/v2/resource/dnsrecord/desired.go, service/controller/v2/resource/dnsrecord/resource.go, service/controller/v2/resource/dnsrecord/update.go, service/controller/v2/resource/resourcegroup/resource.go, service/controller/v2/resource/vnetpeering/current.go, service/controller/v2/resource/vnetpeering/delete.go, service/controller/v2/resource/vnetpeering/desired.go, service/controller/v2/resource/vnetpeering/resource.go, service/controller/v2/resource/vnetpeering/update.go, service/controller/v2/resource_set.go
This PR tries to ease the error masking. In case errors are only received and dispatched it does not yield to a lot of benefit to annotate them. IMO the contrary is the case. The stack should be as pure and clean as possible. In almost all cases only the creator of an error is able to annotate really relevant information. Any other information is more or less useless garbage we carry for nothing. The trace is the important part which is way easier to scan in case it stays clean. When you debug you follow the execution flow by hard line numbers. In case of serious problems you have to get into the code and read and understand it. No annotation of dispatched errors can help here. Annotations almost always only make sense when an error is created at the root of its origin.
=> simplifies error masking of errors that are only dispatched

service/controller/cluster.go
That is a left over from testing. It does not hurt but using the default values again is just fine.
=> sets informer settings explicitly to default values

service/controller/v2/resource/vnetpeering/current.go
During testing I figured out there is a problem with cluster deletion. Right now the vnet peerings are not deleted. This PR fixes the problem. I tested this successfully on `godsmack`.
=> does not cancel resource on deletion when resources should be removed

service/controller/v2/resource/instance/create.go, service/controller/v2/resource/instance/delete.go, service/controller/v2/resource/instance/error.go, service/controller/v2/resource/instance/resource.go, service/controller/v2/resource_set.go
Towards https://github.com/giantswarm/giantswarm/issues/3272. The idea here is to have a new resource which manages the update mechanism as we want to implement it for Azure. 
> AFAIK we use the resource manager magic via the Azure API. Deployments are reconciled constantly. There is something like scale set models. Once the model is updated instances can be updated to use it. The currently used upgrade strategy is `manual` which means we have to trigger the instance update. We want to leverage this approach in order to have control over the draining. There is https://github.com/giantswarm/node-operator which we already integrated into the `aws-operator` and `kvm-operator`. During the reconciliation in the `azure-operator` we want to list all instances and check if they have to be …
=> adds new instance resource and wires it

service/controller/v2/arm_templates/main.json, service/controller/v2/arm_templates/security_groups_setup.json, service/controller/v2/cloudconfig/master_extension.go, service/controller/v2/cloudconfig/render.go, service/controller/v2/cloudconfig/render_test.go, service/controller/v2/cloudconfig/template.go, service/controller/v2/cloudconfig/types.go, service/controller/v2/resource/deployment/deployment.go, service/controller/v2/version_bundle.go
Task: https://github.com/giantswarm/giantswarm/issues/3268
Idea is that we are managing ingress load balancer with Kubernetes itself. So in this change:
- remove ingress load balancer creation from ARM templates
- add systemd unit that creates kubernetes service type load balancer (with external-dns annotation to create DNS A record)
=> manage ingress load balancer by kubernetes

service/controller/v2/cloudconfig/types.go, service/controller/v2/key/key.go, service/controller/v2/key/key_test.go
I need full cluster domain for my ingress load balancer. But for some reason i've used DNSZonePrefixIngress that returns only `xxxxx.k8s`, but i need full `xxxxx.k8s.gollum.westeurope.gigantic.io`. So added new function that provides cluster doman.
=> Fix ingress dns domain for load balancer

service/controller/v2/arm_templates/main.json, service/controller/v2/arm_templates/route_table_setup.json, service/controller/v2/resource/deployment/deployment.go, service/controller/v2/resource/deployment/resource.go, service/controller/v2/resource/deployment/types.go
Related-to: https://github.com/giantswarm/azure-operator/issues/233
Tested in `godsmack`
This change fixes issue when routes created by Kubernetes controller manager are removed while ARM reconciliation. To avoid this we adding new paramter "initialProvisioning" and deploying route table only on first run. On reconciliation "initialProvisioning" set to "No", which disables route table reconciliation.
=> Prevent routes removal while reconciliation

service/controller/v2/cloudconfig/render.go, service/controller/v2/cloudconfig/template.go
Fixes: https://github.com/giantswarm/azure-operator/issues/232
Patch k8s-addons script instead adding separate systemd unit. Problem that cloud-init applies sequentally and k8s-ingress-loadbalancer was started before k8s-kubelet and blocked whole start up process and caused some units to start (e.g. update-engine)
=> Improve k8scc to prevent update-engine from start

service/controller/v2/arm_templates/main.json, service/controller/v2/arm_templates/security_groups_setup.json
Fixes: https://github.com/giantswarm/azure-operator/issues/242
Disable reconciliation for worker network security group to prevent wiping rules created by Kuberntes.
Similar to https://github.com/giantswarm/azure-operator/pull/239
=> Disable reconciliation for worker network security group

service/controller/v2/version_bundle.go
We use calico 3.0.8 finally, but i forgot to update changelog.
=> Fix typo in changelog

service/controller/v3/version_bundle.go
Othewise operator fails to start with `changelogs must not be empty: invalid bundle`
=> Add dummy changelog entry

service/controller/v3/resource_set.go
Towards: https://github.com/giantswarm/giantswarm/issues/2652
Enable BYOC by making use of guest cluster credentials
`credential-default` secret are in places in every azure installation (godsmack, gollum, ghost, tarantula, victory) and in e2e tests.
=> enable byoc

service/controller/cluster.go, service/controller/v3/resource/dnsrecord/resource.go, service/controller/v3/resource/vpngateway/clients.go, service/controller/v3/resource/vpngateway/resource.go, service/controller/v3/resource_set.go
Follow up on: https://github.com/giantswarm/azure-operator/pull/289#discussion_r202932843
Rename misleading `AzureConfig` to `AzureClientSetConfig`.
=> rename *AzureConfig to *AzureClientSetConfig

service/controller/v3/resource/service/update.go
found a small race condition with reconciliation fo service resource
If the `current service` is read from the early stage then it has no `spec.clusterIP` value and then if we tried to update the service with no `spec.clusterIP` it will throw errors as that value is immutable.
=> service-reconcilation-minor-bugfix

service/controller/v3/cloudconfig/master_extension.go, service/controller/v3/cloudconfig/render.go, service/controller/v3/cloudconfig/render_test.go, service/controller/v3/cloudconfig/template.go, service/controller/v3/cloudconfig/types.go, service/controller/v3/cloudconfig/worker_extension.go, service/controller/v3/version_bundle.go
Fixes: https://github.com/giantswarm/giantswarm/issues/3847
Fixes: https://github.com/giantswarm/azure-operator/issues/113
In Azure you can set LUN ID, when attaching disk to VM. CoreOS supplied with special udev rules for Azure that create symlinks in `/dev/disk/azure/scsi1/lunX`, where `X` is the lun that was specified while attaching.
=> Fix Azure disk mounts

service/controller/v4/cloudconfig/template.go
Add missing flag to skip `/var/lib/calico/nodename` if it's not available. This was already done for aws and kvm, but missed in Azure.
=> Add compatibility mode for new Calico

helm/azure-operator-chart/templates/credential-default.yaml, integration/setup/setup.go
Towards: https://github.com/giantswarm/giantswarm/issues/3815
Add `credential-default` which is now required by azure-operator to operate tenant cluster.
=> add credential-default to helm chart

service/controller/v5/cloudconfig/template.go, service/controller/v5/version_bundle.go
Part of: https://github.com/giantswarm/giantswarm/issues/4159
Makes calico QoS policy guaranteed.
=> Add resource limits for install-cni container and make it initContainer.

service/controller/v3/key/key.go, service/controller/v3/resource/instance/create.go, service/controller/v3patch1/key/key.go, service/controller/v3patch1/resource/instance/create.go, service/controller/v4/key/key.go, service/controller/v4/resource/instance/create.go, service/controller/v5/key/key.go, service/controller/v5/resource/instance/create.go
This effectively blocked us from making upgrades on clusters with more
that 10 workers.
It also fixes a problem with instance names that have ID > 10. Apparently base 36 is used to create those names. For more details see https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-instance-ids#scale-set-vm-computer-name.
=> v3, v3patch1, v4, v5: fix vmss instances paging

Gopkg.lock, service/controller/v3patch2/cloudconfig/cloud_config.go, service/controller/v3patch2/cloudconfig/master_extension.go, service/controller/v3patch2/cloudconfig/render.go, service/controller/v3patch2/cloudconfig/worker_extension.go, service/controller/v4patch1/cloudconfig/cloud_config.go, service/controller/v4patch1/cloudconfig/master_extension.go, service/controller/v4patch1/cloudconfig/render.go, service/controller/v4patch1/cloudconfig/worker_extension.go, vendor/github.com/giantswarm/k8scloudconfig/CHANGELOG.md, vendor/github.com/giantswarm/k8scloudconfig/v_3_5_2/cloudconfig.go, vendor/github.com/giantswarm/k8scloudconfig/v_3_5_2/error.go, vendor/github.com/giantswarm/k8scloudconfig/v_3_5_2/master_template.go, vendor/github.com/giantswarm/k8scloudconfig/v_3_5_2/render_asset_content.go, vendor/github.com/giantswarm/k8scloudconfig/v_3_5_2/types.go, vendor/github.com/giantswarm/k8scloudconfig/v_3_5_2/worker_template.go, vendor/github.com/giantswarm/k8scloudconfig/v_3_6_3/cloudconfig.go, vendor/github.com/giantswarm/k8scloudconfig/v_3_6_3/error.go, vendor/github.com/giantswarm/k8scloudconfig/v_3_6_3/master_template.go, vendor/github.com/giantswarm/k8scloudconfig/v_3_6_3/render_asset_content.go, vendor/github.com/giantswarm/k8scloudconfig/v_3_6_3/types.go, vendor/github.com/giantswarm/k8scloudconfig/v_3_6_3/worker_template.go, vendor/github.com/giantswarm/k8scloudconfig/v_3_7_3/cloudconfig.go, vendor/github.com/giantswarm/k8scloudconfig/v_3_7_3/error.go, vendor/github.com/giantswarm/k8scloudconfig/v_3_7_3/master_template.go, vendor/github.com/giantswarm/k8scloudconfig/v_3_7_3/render_asset_content.go, vendor/github.com/giantswarm/k8scloudconfig/v_3_7_3/types.go, vendor/github.com/giantswarm/k8scloudconfig/v_3_7_3/worker_template.go
wired new kubernetes versions in v3patch2 and v4patch1
v3patch2 => k8s 1.10.11
v4patch1 => k8s 1.11.5
CVE-2018-1002105: proxy request handling in kube-apiserver can leave
vulnerable TCP connections
https://github.com/kubernetes/kubernetes/issues/71411
=> Update kubernetes (CVE-2018-1002105)

helm/azure-operator-chart/templates/rbac.yaml, service/collector/client.go, service/collector/resource_group.go, service/collector/set.go
Towards https://github.com/giantswarm/giantswarm/issues/3581
```
$ curl -Ss localhost:8000/metrics | grep azure_operator_resource_group_info
azure_operator_resource_group_info{id="/subscriptions/1be3b2e6-497b-45b9-915f-eb35cae23c6a/resourceGroups/54k5t",location="westeurope",managed_by="azure-operator",name="54k5t",state="Succeeded"} 1
azure_operator_resource_group_info{id="/subscriptions/1be3b2e6-497b-45b9-915f-eb35cae23c6a/resourceGroups/5dpdu",location="westeurope",managed_by="azure-operator",name="5dpdu",state="Succeeded"} 1
azure_operator_resource_group_info{id="/subscriptions/1be3b2e6-497b-45b9-915f-eb35cae23c6a/resourceGroups/6cs7a",location="westeurope",managed_by="azure-operator",name="6cs7a",state="Succeeded"} 1
azure_operator_resource_group_info{id="/subscriptions/1be3b2e6-497b- …
```
=> Adds resource group collector

service/collector/set.go, service/collector/vpn_connection.go, service/service.go
Towards: giantswarm/giantswarm#3581
Provide informations about VPN connections via `/metrics` endpoint.
```
$ curl -Ss localhost:8000/metrics|grep azure_operator_vpn_connection_info                                                                                        
azure_operator_vpn_connection_info{connection_status="Connected",connection_type="IPsec",id="/subscriptions/1be3b2e6-497b-45b9-915f-eb35cae23c6a/resourceGroups/godsmack/providers/Microsoft.Network/connections/godsmack-vpn-connection-0",location="westeurope",name="godsmack-vpn-connection-0",provisioning_state="Succeeded"} 1
azure_operator_vpn_connection_info{connection_status="Connected",connection_type="IPsec",id="/subscriptions/1be3b2e6-497b-45b9-915f-eb35cae23c6a/resourceGroups/godsmack/providers/Microsoft.Network/connecti …
```
=> vpn collector

service/collector/deployment.go
Towards https://github.com/giantswarm/giantswarm/issues/4920. The PM is about stuck deployments. The idea is to track the `Updating` state and have an alert when it appears longer than two hours or something like this.
=> adds 'Running' provisioning state to deployment collector

Gopkg.lock, vendor/github.com/giantswarm/statusresource/Gopkg.lock, vendor/github.com/giantswarm/statusresource/Gopkg.toml, vendor/github.com/giantswarm/statusresource/create.go
Update latest statusresource in order to get node labels into node list in
AzureConfig.Status for older clusters as well (without cluster scaling/update).
=> Vendor update statusresource

service/controller/v4patch1/resource/migration/resource.go, service/controller/v5/resource/migration/resource.go
Fixes https://github.com/giantswarm/giantswarm/issues/5251
Default credential secret should be set when the string is `== ""` and not `!= ""`.
=> migration: fix setting default credential secret

service/controller/v4patch2/resource/migration/resource.go
Towards https://github.com/giantswarm/giantswarm/issues/5251
We fixed this in https://github.com/giantswarm/azure-operator/pull/456 for v4patch1 and v5, but apparently missed this one.
=> Fix incorrect equality check for default credential

.circleci/config.yml
This PR replicates the same behaviour as for AWS. Note that this also implies not running e2e tests on merge to master.
=> enable hold target upfront

service/controller/v6/cloudconfig/cloud_config.go, service/controller/v7/cloudconfig/master_template.go
during https://github.com/giantswarm/giantswarm/issues/3585 testing i found that we actually dont apply loadbalancer manifest to the cluster so no ingress access is possible that seems to be wrong
fixing for WIP and also  backporting to current active release
=> fix-missing-ingress-loadbalancer

.circleci/config.yml, README.md, helm/azure-operator-chart/Chart.yaml, helm/azure-operator-chart/templates/deployment.yaml, helm/azure-operator-resource-chart/Chart.yaml
Towards: https://github.com/giantswarm/giantswarm/issues/5206
This PR enable tagged version to be built and released.
What are the results in case a `v1.0.2` tag  is created:
- docker image `quay.io/giantswarm/azure-operator:1.0.2`
- helm chart `quay.io/giantswarm/azure-operator-chart@1.0.2`
- github v1.0.2 release with `azure-operator-chart-1.0.2.tgz` asset
Breaking change:
- ~chart version for untagged commit will change from `1.0.0-<sha>` to `v0.0.0-<sha>`~
Manual update:
- circleci token has to be updated with full access to private and public github repositories in order for architect to be able to publish github releases. see `repo` in "Available scopes" https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/#available-scopes
=> build and release tags

service/controller/v5/resource/encryptionkey/delete.go, service/controller/v6/resource/encryptionkey/delete.go, service/controller/v7/resource/encryptionkey/delete.go
I see a lot of clusters on Azure being stuck in deleting CRs. This PR should improve at least this issue.
> {"caller":"github.com/giantswarm/azure-operator/vendor/github.com/giantswarm/operatorkit/controller/resource/retryresource/resource_wrapper.go:98","controller":"azure-operator","event":"delete","level":"warning","loop":"2266","message":"retrying due to error","object":"/apis/provider.giantswarm.io/v1alpha1/namespaces/default/azureconfigs/miv40","resource":"encryptionkeyv7","stack":"[{/go/src/github.com/giantswarm/azure-operator/vendor/github.com/giantswarm/operatorkit/controller/resource/retryresource/resource_wrapper.go:91: } {/go/src/github.com/giantswarm/azure-operator/service/controller/v7/resource/encryptionkey/delete.go:22: } {secrets \"miv40-certificate-encryption\" not …
=> make error handling of encryption key deletion more graceful

integration/setup/common.go
We dropped the `NodeConfig` CR recently and have to consider the `DrainerConfig` CR now.
=> fix waiting for node-operator being installed

service/controller/v8/templates/ignition/default_storage_class.go
Current Kubernetes version complaints about `default` storage because of having an old annotation parameter.
=> Delete beta from default storage class

service/controller/v9/blobclient/error.go, service/controller/v9/key/error.go, service/controller/v9/resource/containerurl/error.go, service/controller/v9/resource/encryptionkey/error.go, service/controller/v9/resource/instance/error.go
towards https://github.com/giantswarm/giantswarm/issues/6569
=> Remove executionFailedError matchers to align with fmt

.circleci/config.yml, helm/azure-operator-chart/templates/deployment.yaml
Towards: https://github.com/giantswarm/giantswarm/issues/6557
Remove `.DockerTag` as we only want to use either the old `.SHA` or the new `.Version`.
Going with old way here, as we are now focusing on aws-operator.
=> remove support for .DockerTag and releases

service/collector/usage.go
Towards https://github.com/giantswarm/giantswarm/issues/6426
Same as done here https://github.com/giantswarm/cluster-service/commit/135da30bc9f30b6dc2831f9e669620a140d09ef4 we improve the scraping so a failure of scraping external resources that might be nonresponsive does not put the service down from a Prom perspective and trigger us with annoying `TargetDown` pages
=> Improve scrape of usage

helm/azure-operator-chart/Chart.yaml, helm/azure-operator-resource-chart/Chart.yaml
Towards: https://github.com/giantswarm/giantswarm/issues/7044
This reverts commit 05f0061f06e069268eb640af38f2e2e018aa73ca.
This PR revert the chart version to fixed `1.0.0-<sha>`. So we do not rely on the version detected by architect which is going to change https://github.com/giantswarm/architect/pull/335
=> Revert "build and release tags (#499)"

service/controller/v10patch1/version_bundle.go, service/controller/v10patch2/version_bundle.go
Towards https://github.com/giantswarm/giantswarm/issues/7302 and https://github.com/giantswarm/giantswarm/issues/7257
I made a mistake in the previous PR and updated the version bundle of `v10patch1` instead of `v10patch2`. This corrects that mistake and adds the kubernetes change to the changelog.
=> Release for kubernetes 1.14.8

service/controller/v12/resource/instance/deployment.go, service/controller/v12/resource/instance/template/main.json, service/controller/v12/resource/instance/types.go
There is a `DockerVolumeSizeGB` field in the `AzureConfig` CRD that allows customizing the Azure disk mounted on `/var/lib/docker` for both masters and workers.
We are not using that field yet in the VMSS template, and we hardcoded 50Gb size for the docker disk.
This PR aims at using the CRD field for sizing the docker disk.
I tested it by setting the Disk size manually on the CR and it worked just fine.
=> Using CR field to decide docker volume size

service/controller/v12/resource/instance/template/vmss.json
The `cluster-autoscaler` auto-discovery feature needs that we tag our VMSS. These labels will be later passed as parameters to `cluster-autoscaler`, so that the autoscaler knows which VMSS to scale.
Any tag can be used, but for consistency sake, I've chosen the same tags that we are using on AWS for `cluster-autoscaler`.
=> Tag for autoscaling

helm/azure-operator-chart/templates/deployment.yaml, helm/azure-operator-chart/values.yaml
Updating the `Deployment` object to a more recent `apiVersion`, since it could lead to problems, like those fixed here https://github.com/giantswarm/aws-operator/pull/2077.
=> Use apps/v1 for deployment

Gopkg.lock, service/controller/v12/cloudconfig/master_template.go, service/controller/v12/cloudconfig/worker_template.go, service/controller/v12/key/key.go, service/controller/v12/resource/instance/create.go, service/controller/v12/resource/instance/create_test.go, service/controller/v12/resource/instance/deployment.go, service/controller/v12/resource/instance/template/main.json, service/controller/v12/resource/instance/types.go, service/controller/v12/templates/ignition/kubelet_mount_unit.go, service/controller/v12/templates/ignition/small.go, vendor/github.com/giantswarm/apiextensions/pkg/apis/provider/v1alpha1/azure_types.go
The goal of this PR is to add to the master and workers template a new volume mounted on /var/lib/kubelet.
The volume size will be adjustable by modifying the CR AzureConfig.
This PR also includes a fix on the previously existing Docker volume which wasn't mounted correctly on worker nodes.
The related issue is https://github.com/giantswarm/giantswarm/issues/7526
=> Added new virtual disk on /var/lib/kubelet for workers and master

Gopkg.lock, service/controller/v10patch2/resource/instance/types.go, service/controller/v10patch2/version_bundle.go, vendor/github.com/giantswarm/k8scloudconfig/CHANGELOG.md, vendor/github.com/giantswarm/k8scloudconfig/v_4_8_1/cloudconfig.go
Towards https://github.com/giantswarm/giantswarm/issues/7302
`v10patch2` with Kubernetes 1.14.8 was already merged to master but not yet released. This PR bumps it to Kubernetes 1.14.9 before 8.6.0 goes out.
=> Release 8.6.0 with Kubernetes 1.14.10

Gopkg.lock, Gopkg.toml, vendor/github.com/giantswarm/statusresource/resource.go
Towards giantswarm/giantswarm#7675
Confirming https://github.com/giantswarm/statusresource/pull/45 works for all providers.
=> vendor: updated statusresource

service/controller/v12/resource/instance/checksum.go
By use of `io.Copy(Writer, Reader)` this change skips making of full copy of ARM
template in temporary variable before computing hash.
=> Compute deployment template digest by directly reading response body

.circleci/config.yml
Towards https://github.com/giantswarm/giantswarm/issues/8767
We currently have tests for the `wip` version, and the `current` version (the latest release). This PR removes tests for the `current` version, since that was tested already when it was `wip`.
Only the `updating` test for `current` is kept, as this test checks the update process from `wip` to `current`.
=> Remove e2e tests for already released version

service/controller/v13/cloudconfig/base_extension.go, service/controller/v13/cloudconfig/types.go, service/controller/v13/resource/deployment/template/main.json, service/controller/v13/templates/ignition/ingress_lb.go, service/controller/v13/version_bundle.go
This change picks up name of the already allocated public IP and assigns it as
annotation to ingress LB.
This is the complementary PR for https://github.com/giantswarm/azure-operator/pull/604
Towards https://github.com/giantswarm/giantswarm/issues/6636
=> Re-use already allocated Public IP for ingress LB

service/controller/v13/resource/instance/create_provisioning_successful.go
When tenant cluster workers are scaled, it's enough that VMSS deployment gets
updated and then we just consider it done. We don't want to re-image master[s]
nor replace worker nodes with new ones. We only want to update the VMSS
deployment and that configures the VMSS accordingly.
=> Ensure that scaling shortcut is active

service/controller/v13/resource/instance/create_wait_for_nodes_to_become_ready.go, service/controller/v13/resource/instance/error.go
It can happen that tenant is not reachable and therefore the code should check
for missing client and keep the state until it's there.
=> Add check for mising tenant k8s client

service/controller/v12/version_bundle.go, service/controller/v13/resource/instance/types.go, service/controller/v13/version_bundle.go
So, coreOS version was bumped in v12 (2.8.0) version's changelog from v2191.5.0 to v2247.6.0 but that wasn't done.
I changed the v12 version_bundle to change the coreOS version to the used one (2191.5.0).
Same thing about v13 (2.9.0) which was copied from (2.8.0).
=> Fix coreOS version

service/controller/v14/key/key.go, service/controller/v14/resource/instance/types.go, service/controller/v14/version_bundle.go
Bumped the coreos version to 2303.4.0 (supported in westeurope, francecentral and germanywest) before we forget to do that.
=> Bumped coreOS before we forget

helm/azure-operator/templates/deployment.yaml
Merging without approval.
Trying to fix 
```
failed to create resource: Deployment.apps "azure-operator-master" is invalid: [spec.template.spec.containers[0].volumeMounts[0].name: Not found: "azure-operator-master-configmap", spec.template.spec.containers[0].volumeMounts[1].name: Not found: "azure-operator-master-secret"]
```
=> Fix volume names in chart

pkg/project/project.go, pkg/project/version_bundle.go, service/controller/resource_set.go
Towards https://github.com/giantswarm/giantswarm/issues/8637
We want to invert how the project version is maintained and now that
it isn't injected during the build from git data, we can remove the
separate concept of _bundle version_ and replace it with just _version_.
=> pkg, service: replace `bundleVersion` with `version`

pkg/project/version_bundle.go
I forgot to update the version bundle info regarding the k8s version used.
=> Update exposed info about using k8s 1.16.7

helm/azure-operator-chart/templates/deployment.yaml, helm/azure-operator/templates/deployment.yaml
Towards: giantswarm/giantswarm#9173
Same change from in https://github.com/giantswarm/aws-operator/pull/2164 to prevent MultipleOperatorsRunningSameBundleVersion fires during an operator update.
=> Change Deployment rollout strategy to Recreate

service/collector/vmss_rate_limit.go
Same changes as https://github.com/giantswarm/azure-operator/pull/708
=> Already checked subscriptions should not be used again

service/collector/vmss_rate_limit.go
This makes the vmss exporter to work even when the 429 is firing
=> Return meaningful values for api rate metrics even when 429 is firing

service/collector/client.go
We have two secrets with different client id's, but they use the same subscription id. Two different clients can see the same resource groups since they use the same subscription. This makes the metrics endpoint to fail
This groups the clients by subscription id, only exposing once metrics for every subscription id.
=> Avoid collecting metrics twice

client/azure_client_set.go, client/azure_client_set_test.go
Never retry on HTTP 429 (TooManyRequests) and in other cases retry only once in
Azure SDK clients.
=> Prevent infinite retries in general and on HTTP 429 completely

service/controller/resource/instance/create_wait_for_nodes_to_become_ready.go
Node status conditions have type and reason and both must be matched correctly
in order to detect node readiness correctly. This change mainly affects cluster
upgrade.
=> Fix isReady() when ensuring node is ready during instance upgrades

service/collector/rate_limit.go, service/collector/usage.go, service/collector/vmss_rate_limit.go
Fixes https://github.com/giantswarm/giantswarm/issues/9298
We were getting errors due to metrics being collected twice
```
An error has occurred while serving metrics:
collected metric "azure_operator_rate_limit_vmss_instance_list_parsing_errors" { counter:<value:150 > } was collected before with the same name and label values
```
After removing the lines in the changes, metrics seem to work normally.
=> No need to send to metrics channel already registered metrics

helm/azure-operator-chart/templates/deployment.yaml, helm/azure-operator-chart/templates/service.yaml
Fixes https://github.com/giantswarm/giantswarm/issues/9440
When redeploying `thiccc` branch, kubernetes complained because the label `version` is immutable using `apps/v1` apiVersion. Instead of using the git sha as version just harcode the `thiccc` string, since there will be only one `thiccc` deployment.
=> Hardcode selector label since it can't be changed when using apps/v1 apiversion

service/controller/key/key.go, service/controller/resource/instance/create_deployment_completed.go, service/controller/resource/instance/create_deployment_uninitialized.go, service/controller/resource/instance/deployment.go, service/controller/resource/instance/resource.go
This PR disables the multi AZ feature for the germanywestcentral region, because AZs are not supported in there.
Note: e2e tests are failing for a different reason, Celestial is working to fix that.
Note2: this has been tested in both GWC and in another region and it seems to be working just fine.
=> Disable AZs from GWC because they're not supported.

helm/azure-operator-chart/templates/configmap.yaml, helm/azure-operator-chart/templates/deployment.yaml, helm/azure-operator-chart/templates/psp.yaml, helm/azure-operator-chart/templates/pull-secret.yml, helm/azure-operator-chart/templates/rbac.yaml, helm/azure-operator-chart/templates/secret.yaml, helm/azure-operator-chart/templates/service-account.yaml, helm/azure-operator-chart/templates/service.yaml, helm/azure-operator-chart/values.yaml
These changes prepare Helm deployment templates to get cluster component
versions from releases instead of k8scloudconfig.
Towards https://github.com/giantswarm/giantswarm/issues/8436
=> Helm preparation to get component versions from releases

helm/azure-operator/Chart.yaml, helm/azure-operator/templates/_helpers.tpl, helm/azure-operator/templates/configmap.yaml, helm/azure-operator/templates/deployment.yaml, helm/azure-operator/templates/psp.yaml, helm/azure-operator/templates/pull-secret.yml, helm/azure-operator/templates/rbac.yaml, helm/azure-operator/templates/secret.yaml, helm/azure-operator/templates/service-account.yaml, helm/azure-operator/templates/service.yaml, helm/azure-operator/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/8632
Refactor labels out into a template helper to be able to maintain them
in one place and use on multiple objects. This borrows from a structure
of a default chart template in upstream Helm.
Ensure all resources created when the chart is installed have proper
labels, i.e. `$OPERATOR.giantswarm.io/` + `version` - used as selector
together with `app`, as well as `branch` and `commit` - purely
informational.
Also add common labels advocated by Kubernetes
https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/
so that resources can be queried and visualised by shared tooling.
=> helm: Ensure proper labels on all resources

service/controller/resource/instance/instance_update_watchdog.go
This PR adds a check to the VMSS API rate limit current value before scaling up one worker node in the cluster during the upgrade.
Adding a node is the most stressful operation from a VMSS API calls point of view.
If there are not at least 50% of the API calls available, it'll wait for next reconciliation loop.
Open to suggestions.
=> Check VMSS rate limit values before proceeding with VMSS changes.

helm/azure-operator/templates/service.yaml
We are disabling Prometheus scrapping on `master` branch. We will keep collecting metrics from `thiccc` branch only.
=> Disabled Prometheus scrapping

Gopkg.lock, service/controller/resource/instance/create_cluster_upgrade_requirement_check.go
It is difficult to detect different change scenarious with Azure APIs /
infrastructure and that has invoked full upgrade process e.g. when creating
cluster or scaling despite of many checks that try to test for such situation.
On principal rolling of node should not be needed other than when clusters are
upgrading or when certificates need renewal. This change introduces first of
these so upgrade process only executes through when there are nodes with old
azure-operator version labels. Similar case for expiring certificates should be
added later if needed.
=> Only roll nodes when they aren't in sync with provider operator

service/controller/resource/instance/create_cordon_old_workers.go, service/controller/resource/instance/deployment.go, service/controller/resource/instance/template/vmss.json
See https://github.com/giantswarm/giantswarm/issues/9921
We try to use a different approach to distinguish between old nodes and new nodes during an upgrade.
Instead of relying on the `Latest model` field provided by azure, we use a tag we set to the VMSS containing the release version.
We hope that the tag is propagated to the instances of the VMSS only when they are upgraded to the new model.
=> New node detection

pkg/project/project.go
See [releases pull request](https://github.com/giantswarm/releases/pull/216) for more details.
=> Bump to v3.0.5 for release v11.2.2

service/controller/resource/instance/create_cordon_old_workers.go, service/controller/resource/instance/create_drain_old_worker_nodes.go, service/controller/resource/instance/create_terminate_old_workers.go
This PR removes all usages of the LastModelApplied field of the VMSS Instance type because it proved to be unreliable, at least on germany west central.
There is only one usage for it at the moment (in the update phase) but I guess we can't remove it from there.
=> Get rid of LastModelApplied checks

.circleci/config.yml
Currently, azure-operator doesn't automatically handle the rollout of master instances where there are changes on the ARM template. This makes this e2e test to fail.
We will enable it back when this is fixed.
=> Disable cluster-state e2e test

service/controller/resource/instance/create_scale_workers.go, service/controller/resource/instance/internal/vmsscheck/error.go, service/controller/resource/instance/internal/vmsscheck/guard_job.go, service/controller/resource/instance/internal/vmsscheck/vmss.go
I moved the VMSS rate limit check from inside the guard job to just before the upscaling of worker vmss.
The most critical moment during an upgrade in terms of VMSS API calls is when a new node is added.
That's the moment when we need to check for the API to be in a safe state.
=> CHeck for VMSS rates before scaling up worker nodes

service/controller/resource/instance/internal/vmsscheck/vmss.go
This PR fixes a nil pointer error while checking the status of VMSS rate limit during a cluster upgrade
=> Extract the API response correctly during scale up operation

.gitignore, docs/running_e2etests_locally.md, integration/env/common.go, integration/setup/setup.go
With these changes we are able to override the chart package used to install the operator, which allows us to pass a local path so we don't have to push and wait for CI to run tests locally.
I also added documentation on how to run e2e tests locally from dev machine.
=> Override tested operator

pkg/project/project.go
Bump to `4.0.0-dev` or to [`3.1.0-dev`](https://github.com/giantswarm/azure-operator/pull/806), pick your favourite.
=> Version bump to v4.0.0-dev

service/controller/resource/instance/create.go, service/controller/resource/instance/create_scale_workers.go, service/controller/resource/instance/create_wait_for_nodes_to_become_ready.go, service/controller/resource/instance/create_wait_new_vmss_workers.go, service/controller/resource/instance/status.go
Wait for new VMSS workers to be ready before draining old ones during flatcar migration.
=> Wait for new VMSS workers to be ready before draining

service/controller/resource/release/create.go
It would be cool to always use the same formatting when talking about releases. Our releases are named like `vX.Y.Z`, so for consistency sake, we should aim to always use that format.
Our operator was expecting the format `X.Y.Z`, without the leading "v", so I'm changing it to make it work with both.
In the future, when we don't have older azure-operator versions, we can change our frontends to use the leading "v" format everywhere.
=> Release name in annotation may or may not contain a leading 'v'

integration/setup/catalog.go, integration/setup/common.go, integration/setup/provider.go, integration/setup/release.go, integration/setup/setup.go, service/controller/controllercontext/context.go, service/controller/key/error.go, service/controller/key/key.go, service/controller/resource/blobobject/desired.go, service/controller/resource/instance/deployment.go, service/controller/resource/masters/deployment.go, service/controller/resource/release/create.go
We want an easy way to fetch info from a `Release`.
This also allows us to use it during e2e tests. I'm not changing the logic much, but with these changes we are reading components versions from the `Release` that we install during e2e tests, so that all the info about components is self-contained in the `Release` CR.
I create the `Release` as the first step of the setup and then pass it to other steps, so every step can fetch information from the `Release`.
=> Centralize methods to gather info from Release

CHANGELOG.md, client/senddecorator/ratelimit_circuitbreaker.go
<details>
<summary>While creating a new cluster I received this panic</summary>
```
D 05/08 15:23:00 /apis/provider.giantswarm.io/v1alpha1/namespaces/default/azureconfigs/uuqe4 containerurl finding storage account | azure-operator/v3/service/controller/resource/containerurl/create.go:18 | controller=azure-operator | event=update | loop=11 | version=149419926
E0508 15:25:28.978530       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 483 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1925540, 0x2cc2d70)
/go/pkg/mod/k8s.io/apimachinery@v0.16.5-beta.1/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0) …
```
=> Only inspect response HTTP status code if there were no errors doing the request

.gitignore, scripts/flowchart.sh, scripts/flowchart.template.html
Two things added:
- HTML file with flowchart template
- bash script for generating flowchart
It works for release `11.4.0` and newer.
Usage of script:
```sh
./flowchart.sh azure-operator-master \
--tenant-cluster $tenant_cluster_id \
--open-browser \
--kube-context $kubectl_context \
--output $flowchart_output_path
./flowchart.sh azure-operator-master -t $tenant_cluster_id -b \
-c $kubectl_context \
-o $flowchart_output_path
```
In the example `azure-operator-master` is the name of `App` CR. HTML file with the flowchart will be generated in the current directory and the default browser will be opened.
Notes about arguments/flags:
- `--tenant-cluster` | `-t` is optional, if it is specified the flowchart will include only state transitions for the specified tenant cluster, otherwise it will …
=> State machine flowchart generation

.circleci/config.yml, integration/config/setup.sh, integration/env/azure.go, integration/setup/catalog.go, integration/setup/provider.go, integration/test/clusterdeletion/.env, integration/test/clusterstate/.env, integration/test/cptcconnectivity/.env, integration/test/multiaz/.env, integration/test/scaling/.env, integration/test/update/.env, integration/test/update/provider.go
- Use latest architect-orb version so we don't have to install Helm during e2e tests.
- Use a bigger CircleCI machine.
- Use architect to calculate latest operator release, instead of requesting that info from catalog.
=> Calculate latest operator release version using architect

pkg/credential/credential.go, pkg/credential/credential_test.go, pkg/label/label.go, service/controller/cluster.go, service/controller/resource/ipam/subnet_collector.go
When migrating to multi tenant service principals, the code will fail to manage tenant cluster resources unless the Service Principal passed as parameter has been invited to customer's Active Directory, and assigned the `Owner` IAM role.
This PR changes the code so that if the credential secret has a label/annotation, all fields (clientid, clientsecret, tenantid...) are used to authenticate, to make it work like before. When service principals migration is over we can remove the label/annotation.
=> Use single tenant service principal if secret is labeled

scripts/migrate-nginx-ingress-controller.sh
Towards https://github.com/giantswarm/giantswarm/issues/9962
The NGINX LB migration script was introduced as part of https://github.com/giantswarm/azure-operator/pull/827
Now it has further been tested, and nature changed so that it's intended to be run after tenant cluster upgrade (say from 11.3.3 to 11.4.0) instead of before the upgrade as was the initial intention. With this, scope of the script changed too.
Script is still not complete/sufficient, it may be extended to automate cleanup of old LB Service, ensure Azure LB backend pool is unchanged and still works after the removal. @whites11 is looking into that. For now I'll cover those old LB Service cleanup steps separately, with migration steps instructions in the 11.4.0 release notes.
=> Update NGINX LB migration script

client/factory.go, pkg/credential/credential.go, pkg/credential/credential_test.go, pkg/credential/spec.go, pkg/project/project.go, service/controller/cluster.go, service/controller/resource/instance/create_deployment_completed.go, service/controller/resource/instance/create_deployment_initialized.go, service/controller/resource/instance/create_deployment_uninitialized.go, service/controller/resource/instance/create_scale_workers.go, service/controller/resource/instance/create_terminate_old_vmss.go, service/controller/resource/instance/create_terminate_old_workers.go, service/controller/resource/instance/deployment.go, service/controller/resource/ipam/subnet_collector.go, service/controller/resource/masters/create_deallocate_legacy_instance.go, service/controller/resource/masters/create_delete_legacy_vmss.go, service/controller/resource/masters/create_deployment_completed.go, service/controller/resource/masters/create_deployment_initialized.go, service/controller/resource/masters/create_deployment_uninitialized.go, service/controller/resource/masters/create_master_instances_upgrading.go, service/controller/resource/masters/create_restart_kubelets.go, service/controller/resource/masters/deployment.go, service/controller/resource/nodes/instances.go, service/service.go
The factory that we use to create Azure clients is coupled to our `AzureConfig` CR. If we change to CAPI types, we can't use the factory. This is blocking me for the node pools story.
I thought that one potential solution we could make it CR independant by creating a credentials provider. In our case, the provider is kubernetes (we use k8s secrets). And the factory doesn't know how to read the credentials: it asks the credentials provider.
What do you think?
=> Make client factory not depend on AzureConfig

service/controller/cloudconfig/types.go, service/controller/key/key.go, service/controller/machine_pool.go, service/controller/resource/cloudconfig/create.go, service/controller/resource/cloudconfig/current.go, service/controller/resource/cloudconfig/delete.go, service/controller/resource/cloudconfig/desired.go, service/controller/resource/cloudconfig/error.go, service/controller/resource/cloudconfig/mock.go, service/controller/resource/cloudconfig/resource.go, service/controller/resource/cloudconfig/types.go, service/controller/resource/cloudconfig/update.go, service/controller/resource/cloudconfig/update_test.go, service/controller/resource/containerurl/create.go, service/controller/resource/deployment/deployment.go, service/controller/resource/encryptionkey/create.go, service/controller/resource/encryptionkey/delete.go, service/controller/resource/instance/deployment.go, service/controller/resource/masters/deployment.go, service/service.go
Towards https://github.com/giantswarm/giantswarm/issues/11926
We have an operatorkit handler that saves an Azure blob object with the `cloud-config` files required for our nodes. In order to render these files we need some information about the cluster being created, and until now, this operatorkit resource was executed receiving the old `AzureConfig` CR which contained all the required information.
But now we want to create the `cloud-config` files when we create different node pools. So I copied the whole `blobobject` resource and call it `cloudconfig`. They are the same, but
- `cloudconfig` will be executed on `AzureMachinePool` events, using info from `AzureMachinePool`, `AzureCluster`, `MachinePool` and `Cluster`.
- `blobobject` will be executed on `AzureConfig` events, using info …
=> Create cloud-config handler for CAPI types

service/controller/resource/instance/create_scale_workers.go, service/controller/resource/instance/internal/scalestrategy/incremental.go, service/controller/resource/instance/internal/scalestrategy/interface.go, service/controller/resource/instance/internal/scalestrategy/quick.go
Towards: https://github.com/giantswarm/giantswarm/issues/11995
This PR aims at making configurable (in the future) the strategy we use to scale up worker nodes during cluster upgrades.
Currently we add the worker nodes 1 by 1 until we double the cluster size (done to be gentle with azure APIs and avoid 429s).
With this PR we will switch back to the `quick` strategy of doubling the cluster size in one go.
=> Scale strategy

CHANGELOG.md, pkg/credential/spec.go, service/controller/machine_pool.go, service/controller/resource/cloudconfig/current.go, service/controller/resource/cloudconfig/desired.go, service/controller/resource/cloudconfig/error.go, service/controller/resource/cloudconfig/resource.go, service/controller/resource/cloudconfig/update.go, service/controller/resource/cloudconfig/update_test.go, service/service.go
Towards https://github.com/giantswarm/giantswarm/issues/12024
[The `cloudconfig` handler was copied from the `blobobject` handler](https://github.com/giantswarm/azure-operator/pull/881). The latter was depending on another handler setting values in the controller context. With these changes, the `cloudconfig` handler is independent and doesn't need other handlers.
=> Avoid dependency with controllercontext

CHANGELOG.md, service/controller/key/key.go
towards https://github.com/giantswarm/giantswarm/issues/11585
changes in `k8s-setup-network-env` are here https://github.com/giantswarm/giantswarm/issues/11585
for azure its mostly cosmetic change
=> update-k8s-network-setup image to 2.0

flag/service/registry/registry.go, flag/service/service.go, go.mod, go.sum, helm/azure-operator/templates/configmap.yaml, main.go, service/controller/cloudconfig/cloud_config.go, service/controller/cloudconfig/master_template.go, service/controller/cloudconfig/types.go, service/controller/cloudconfig/worker_template.go, service/controller/cluster.go, service/controller/key/key.go, service/controller/resource/blobobject/desired.go, service/controller/resource/cloudconfig/desired.go, service/service.go
Towards: https://github.com/giantswarm/giantswarm/issues/12126
This PR adds support for docker registry mirrors.
I tested it out and it seems to work just fine.
=> Bump k8scloudconfig to support docker registry mirrors

service/controller/resource/azureclusterconfig/create.go, service/controller/resource/azureclusterconfig/delete.go, service/controller/resource/azureconfig/create.go, service/controller/resource/azureconfig/delete.go
Towards https://github.com/giantswarm/giantswarm/issues/12171
The _legacy_ CR's created should be in the same namespace than the watched `AzureCluster`.
=> Use same namespace than watched CR

service/controller/resource/instance/delete.go, service/controller/resource/instance/error.go
Towards https://github.com/giantswarm/giantswarm/issues/12213
Notice that the target branch is not `master` but the branch for the node pools PR.
When a delete event is watched, we:
- delete the subnet from the `AzureCluster` CR (this will trigger an update event and the `AzureCluster` controller will remove the subnet)
- delete the ARM deployment for the VMSS node pool
- delete the VMSS
=> Handle node pool deletion

service/controller/resource/subnet/error.go, service/controller/resource/subnet/resource.go
Towards https://github.com/giantswarm/giantswarm/issues/12213
Please, notice that the target branch is not `master`, but the `subnet` handler PR.
This will remove subnets that exist in the virtual network but are not defined in the `AzureCluster` object and are not the legacy subnets (masters, workers, vpn subnets).
=> Garbage collect subnets that shouldn't exist after deleting node pools

service/controller/key/key.go, service/controller/resource/spark/create.go, service/controller/resource/spark/delete.go, service/controller/resource/spark/delete_test.go, service/unittest/default_k8sclient.go
Towards https://github.com/giantswarm/giantswarm/issues/12271
When we use the real Ignition Operator, we wouldn't have to worry about the `Secret` deletion from here. 
But should we care about the `Spark` CR deletion? or should the piece that created it in the first place take care of deleting it @giantswarm/team-ludacris? I mean in the future when we have the Ignition operator in place.
=> Delete Spark CR when deleting a node pool

.circleci/config.yml
The goal of this PR is to make circle job dependency a little more elegant.
Before:
After:
From a functional point of view nothing changes
=> change jobs dependencies to make circle graph better

helm/azure-operator/templates/rbac.yaml, service/controller/azure_config.go, service/controller/azure_machine_pool.go, service/controller/cluster.go, service/controller/cluster_test.go, service/controller/key/key.go, service/controller/machine_pool.go, service/controller/machine_pool_test.go, service/service.go, service/unittest/default_k8sclient.go
Towards https://github.com/giantswarm/giantswarm/issues/12428
This PR adds two provider agnostic controllers: machine pool controller and cluster controller. These controllers try to mimic the upstream CAPI provider agnostic controllers.
By setting the `ownerReferences` in our CR's we can leverage Kubernetes garbage collection. This means that if a `Cluster` is deleted, owned resources like `AzureCluster` and `MachinePool` will be deleted (and also `AzureMachinePool` because it's owned by `MachinePool`).
At the moment these controllers only do this small task, so I _inlined_ the handlers inside the controllers. Not sure about this approach though. We could create two new handlers "the normal way" and just reference them from the controllers.
The machine pool controller makes sure that:
- …
=> Added provider agnostic controllers to manager ownerReferences and labels

service/controller/azure_cluster_controller.go, service/controller/azure_config.go, service/controller/azure_machine_pool.go, service/controller/cluster.go, service/controller/machine_pool.go, service/service.go
Use an slice to hold all the controllers and just iterate through it when booting them. I believe it's simpler, and the `Service` is not coupled to the controllers.
=> Use slice of controllers instead of booting one by one

service/controller/cluster.go, service/controller/machine_pool.go, service/controller/resource/clusterownerreference/error.go, service/controller/resource/clusterownerreference/resource.go, service/controller/resource/clusterownerreference/resource_test.go, service/controller/resource/machinepoolownerreference/error.go, service/controller/resource/machinepoolownerreference/resource.go, service/controller/resource/machinepoolownerreference/resource_test.go
Cluster & MachinePool controllers need to be configured with more handlers so
it makes sense to extract embedded handlers to their own packages as others.
There are no logic changes, the implementation is just moved to separate packages.
=> Extract OwnerReference handlers to own packages

service/controller/resource/clusterdependents/error.go, service/controller/resource/clusterdependents/resource.go, service/controller/resource/machinepooldependents/error.go, service/controller/resource/machinepooldependents/resource.go
When deleting cluster, Cluster controller must wait for all cluster related
child CRs before the finalizer is removed. Similar to this, MachinePool
controller must wait for all node pool related CRs to be deleted before
allowing the finalizer to be removed.
This prevents orphaned dependents when CRs are deleted in unspecified order.
=> Add CAPI handlers to wait for dependent CRs on deletion

service/controller/cluster.go, service/controller/machine_pool.go
CAPI dependents deletion handlers wait until all dependent CRs are gone before
removing finalizer from Cluster and MachinePool.
=> Wire CAPI dependents deletion handlers

service/controller/resource/cloudconfigblob/create.go, service/controller/resource/cloudconfigblob/delete.go
When cluster gets deleted, the top level cluster reconciliation deletes whole
resource group. If machinepool cleanup is still in progress, it might happen
that storage account gets deleted before the machine pool is fully gone so
handle the not found error gracefully.
Equally when it's created, the storage account might not be there yet so
cancel resource while waiting for it.
=> Handle missing storage account & blob gracefully on create & delete

integration/test/crmapping/testdata/case-0-create-AzureConfig_AzureConfig.golden, integration/test/crmapping/testdata/case-0-migrate-AzureConfig_AzureConfig.golden, service/controller/resource/capzcrs/create.go, service/controller/resource/capzcrs/create_test.go, service/controller/resource/capzcrs/testdata/azurecluster_with_subnets.yaml, service/controller/resource/capzcrs/testdata/case-3-Ensure-that-AzureCluster-Subnets-are-not-wiped_AzureCluster.golden, service/controller/resource/capzcrs/testdata/case-3-Ensure-that-AzureCluster-Subnets-are-not-wiped_AzureMachine.golden, service/controller/resource/capzcrs/testdata/case-3-Ensure-that-AzureCluster-Subnets-are-not-wiped_Cluster.golden
Generic implementation doesn't preserve original CR spec fields. This is needed
to maintain dynamically managed subnets in AzureCluster.
=> Improve capzcrs CR merging

e2e/test/multiaz/provider.go
```
=== RUN   Test_AZ
{"caller":"github.com/giantswarm/azure-operator/v4/e2e/test/multiaz/multiaz_test.go:48","level":"debug","message":"getting current availability zones","time":"2020-08-26T10:52:49.501237+00:00"}
Test_AZ: multiaz_test.go:17: {"kind":"unknown","annotation":"compute.VirtualMachineScaleSetsClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"ResourceNotFound\" Message=\"The Resource 'Microsoft.Compute/virtualMachineScaleSets/ci-wip-aa48c-19066-worker-ci-wip-aa48c-19066' under resource group 'ci-wip-aa48c-19066' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix\"","stack":[{"file":"/home/circleci/.go_workspace/src/github.com/giantswarm/azure-operator/e2e/tes …
```
=> Fix multiaz e2e tests for nodepools

e2e/env/common.go, e2e/setup/provider.go, e2e/test/multiaz/main_test.go, e2e/test/multiaz/provider.go
`MultiAZ` test needs the node pool id, so that it can assert it has been deployed in the right AZs.
=> Pass node pool ID to test so it can assert later

service/controller/resource/nodepool/create_deployment_uninitialized.go, service/controller/resource/nodepool/deployment.go, service/controller/resource/nodepool/error.go, service/controller/resource/subnet/resource.go
We sometimes hit an error when creating the nodepool ARM deployment because the subnet chosen for the VMSS is still being created. It eventually succeeds but in order to avoid errors as much as possible, I'm canceling the nodepool handler if we don't have the `AzureCluster.Spec.NetworkSpec.subnet.ID` field set for the nodepool subnet. This `subnet.ID` field will be set by the subnet handler when it finds the subnet ARM deployment in a successful state.
=> Cancel nodepool handler if Subnet is not ready yet

pkg/project/project.go, service/controller/azure_config.go, service/controller/resource/capzcrs/create.go, service/controller/resource/masters/delete.go, service/controller/resource/masters/error.go, service/controller/resource/masters/resource.go
For now, when master instances are managed with AzureConfig reconciliation,
deletion of AzureMachines is most natural when deleting the instances as well.
This will change once the tenant cluster control plane is also reconciled by
CAPI&CAPZ types.
=> Delete AzureMachine CRs when deleting master instances

e2e/entityid/generator.go, e2e/env/common.go
New env vars:
- `CLUSTER_ID_PREFIX`: by default it's `ci` (current naming scheme)
- `RANDOMIZE_CLUSTER_ID`: by default it's `false`
- `false`: cluster ID = `cluster ID prefix` + `Tested version` (by default `wip`) + `commit SHA` + `Test name hash`
- `true`: cluster ID = `cluster ID prefix` + `random 5 chars` + `Tested version` (by default `wip`)
=> Customize e2e test cluster ID

e2e/setup/config.go, e2e/test/scaling/error.go, e2e/test/scaling/main_test.go, e2e/test/scaling/provider.go
The e2e tests that were shared between different providers were made in an abstract way, allowing the different providers to provide a set of functions to fulfill a `provider` interface so that the same test could be ran in different providers.
For the scaling test, we had our azure provider that worked with `AzureConfig` by adding and removing workers. We need to make it work with CAPI/CAPZ types now.
=> Make scaling e2e test provider CAPI compatible

e2e/env/azure.go, e2e/test/multiaz/multiaz_test.go
When checking tenant cluster availability zones, the test will use input provided by `AZURE_AZS` environment variable to check the number of availability zones and exact availability zones, instead of comparing to values hard-coded in the test.
This way custom test runs can use different multi-az settings.
=> Improve multi-az e2e test

e2e/setup/bastion.go, e2e/setup/provider.go
```
panic: {"kind":"invalidConfigError","annotation":"spark.Config.ClusterIPRange must not be empty","stack":[{"file":"/root/project/service/controller/resource/spark/resource.go","line":86},{"file":"/root/project/service/controller/azure_machine_pool.go","line":169},{"file":"/root/project/service/controller/azure_machine_pool.go","line":70},{"file":"/root/project/service/service.go","line":347},{"file":"/root/project/main.go","line":66}]}```
=> Pass missing ClusterAPIRange in e2e

service/controller/resource/capzcrs/create.go, service/controller/resource/clusterdependents/resource.go
Cluster deletion is slow, and we can have a race condition where CAPI CRs get recreated during cluster deletion.
We should skip the CR mapping during cluster creation.
=> Skip CR mapping while cluster is being deleted

service/controller/resource/ipam/azure_machinepool_subnet_checker.go
While the cluster is being deleted, there is no need to allocate a subnet for node pool. It's an edge case scenario that could in theory happen if a new node pool is added at roughly the same time while the cluster is being deleted.
=> Skip nodepool IPAM while the cluster is being deleted

service/controller/resource/nodepool/deployment.go, service/controller/resource/spark/create.go
I believe we shouldn't use the `namespace` field from `Spec.InfrastructureRef`. Kubernetes owner references are not able to cross namespace boundaries, so these objects will always be in the same namespace than the owner.
Also, the `namespace` field may actually go away. [There is this discussion about it](https://github.com/kubernetes-sigs/cluster-api/issues/2318) that proposes changing the type of `Spec.InfrastructureRef` to `corev1.LocalObjectReference` since `corev1.ObjectReference` contains too many fields for what's needed (i.e `namespace`).
=> Don't use Infrastructure.Namespace since dependent objects will always be on parent's namespace

service/controller/cloudconfig/base_extension.go, service/controller/cloudconfig/worker_template.go, service/controller/resource/blobobject/desired.go, service/controller/resource/nodepool/deployment.go, service/controller/resource/spark/create.go
We were still using the old cloudconfig files. We need to use the cloudconfig generated by the `spark` handler instead.
=> Use bootstrap cloudconfig generated by spark handler

service/controller/azure_machine_pool.go, service/controller/resource/nodepool/create_cordon_old_workers.go, service/controller/resource/nodepool/create_drain_old_worker_nodes.go, service/controller/resource/nodepool/create_terminate_old_workers.go, service/controller/resource/nodepool/create_wait_for_nodes_to_become_ready.go, service/controller/resource/nodepool/resource.go
Before nodepools we had a handler called `tenantcluster` that added the k8sclient for the tenant cluster to the `controllercontext`. Since `nodepool` handler reacts to `AzureMachinePool`, the `tenantcluster` handler wasn't being called, and we need the client. So I compute it for the `nodepool` handler, but I don't save it in the context.
Not using the `controllercontext` meant passing the tenant cluster client to a bunch of functions.
=> Compute tenant cluster k8sclient instead of relying on context

.circleci/config.yml, e2e/env/azure.go, e2e/setup/provider.go, e2e/test/nodepool/.env, e2e/test/nodepool/error.go, e2e/test/nodepool/main_test.go, e2e/test/nodepool/nodepool_test.go, e2e/test/nodepool/provider.go, service/controller/cloudconfig/worker_template.go, service/controller/key/error.go, service/controller/key/key.go, service/controller/resource/azureconfig/create.go, service/controller/resource/nodepool/status.go, service/controller/resource/spark/create.go, service/controller/resource/subnet/resource.go
We add a new label to the `Node` object in k8s so that it contains the node pool id. This will allow customers to schedule different workloads on different node pools using the label.
=> Label different node pools differently

CHANGELOG.md, service/controller/templates/ignition/default_storage_class.go
Towards: https://github.com/giantswarm/giantswarm/issues/13211
Allow to expand PVCs created using the default storage classes we deploy on tenant clusters.
=> Allow volume expansion for PVCs on the default storage classes

service/controller/resource/azureclusterconfig/create.go, service/controller/resource/azureclusterconfig/credential.go, service/controller/resource/azureclusterconfig/error.go, service/controller/resource/spark/error.go, service/controller/resource/spark/resource.go
Using the same fallback approach in the handlers that own their own logic to fetch the credentials.
=> Use organization credential secret fallback everywhere

pkg/project/project.go, service/controller/resource/nodepool/create_scale_workers.go
When there is a change that requires the rollout of all nodes in a node pool, we apply the deployment and then we proceed with the rollout (we double the size of the NP, cordon old nodes and delete them once drained).
This PR ensures the deployment is applied successfully before it proceeds with the scaling operations, because it happened that we rolled out the nodes despite the deployment was not applied (thus doing the rollout for no reason).
=> Safe scale up

service/controller/resource/spark/create.go, service/controller/resource/spark/error.go
Instead of printing out an error in this case, let's just cancel the whole reconciliation and wait until it's done.
=> Gracefully handle if owner reference is not set

service/controller/resource/deployment/deployment.go
Since there are no built-in workers anymore but each node pool gets own subnet,
it makes more sense to relax security rules to whole tenant cluster CIDR.
=> Use cluster CIDR for security groups & configuration with node pools

pkg/project/project.go, service/controller/resource/azureconfig/create.go, service/controller/resource/spark/create.go
Service discovery was not working on kubernetes unless using the FQDN.
I found [this kubelet property](https://github.com/kubernetes/kubernetes/blob/ee297b6f4d78daaf2f71c78a05203698581ca40a/staging/src/k8s.io/kubelet/config/v1beta1/types.go#L288-L290) that controls the DNS queries, and we are setting that configuration [in our templates](https://github.com/giantswarm/k8scloudconfig/blob/a7a5b5e2054ff0e5d3e5892b035a301c7b4a7653/files/config/kubelet-worker.yaml.tmpl#L9). The problem is that the variable is empty: we are never setting that field.
It was working before because [`kubernetesd` was setting that field](https://github.com/giantswarm/kubernetesd/blob/ceef853b2ec6693f588191be224e48d59db83b6e/service/creator/cluster.go#L92) when creating the `AzureConfig`.
I don't think CAPI/CAPZ …
=> Set cluster domain so that kubernetes DNS service discovery works

pkg/normalize/normalize.go, pkg/normalize/normalize_test.go
In order to normalize free form organization names into namespaces, it must be
converted into lower case string and non-alphanumeric (+ dash) characters must
be converted / stripped. The length of the string must also be limited.
=> Add normalization function for organization namespaces

service/controller/cloudconfig/cloud_config.go, service/controller/key/common.go
We were using the wrong namespace name, because org namespaces are all lowercase, but the organization label is not lowercase.
So I figured: this was the only part in azure-operator where the `organization` namespace shows up. So what about removing that and just use the CR namespace? That way azure-operator doesn't care about the org namespace , or its format: it just uses whatever namespace the CR is in.
=> Encryption secret should live in the same namespace than the CR

CHANGELOG.md, service/controller/resource/nodepool/create_deployment_uninitialized.go, service/controller/resource/nodepool/deployment.go
I realized that we were sending several different requests from the `nodepool` handler to fetch the same VMSS. I tried to fetch it once and pass it around so we can save some requests on every reconciliation loop.
I haven't tested it yet. What do you think?
=> Try to send only one request to VMSS Azure API from nodepool handler

pkg/project/project.go, service/controller/cluster.go, service/controller/machine_pool.go, service/controller/resource/capzcrs/create.go, service/controller/resource/clusterupgrade/create.go, service/controller/resource/clusterupgrade/delete.go, service/controller/resource/clusterupgrade/error.go, service/controller/resource/clusterupgrade/resource.go, service/controller/resource/machinepoolownerreference/resource.go, service/controller/resource/machinepoolupgrade/error.go, service/controller/resource/machinepoolupgrade/resource.go, service/controller/resource/masters/create_cluster_upgrade_requirement_check.go
This change provides first version of implementation that propagates
cluster upgrade in controlled manner over all cluster node pools.
It ensures that Cluster -> AzureCluster CRs have matching release labels
and then propagates these labels to MachinePools one-by-one while
ensuring that there's only one node pool upgrading at a time.
MachinePool labels are then directly ensured on respective
AzureMachinePool CR and corresponding CR's conditions are used to
monitor when given cluster-subset has been upgraded.
=> Upgrade from NP release to NP release

go.mod, go.sum, service/controller/azure_config.go
AzureConfig status conditions aren't used anymore as CAPI & CAPZ types
have superseded those. Cluster & MachinePool, together with
corresponding AzureCluster and AzureMachinePool CRs have more elaborate
status conditions that better reflect the cluster status.
=> Drop unneeded statusresource handler

service/controller/resource/clusterreleaseversion/checkupgradeprogress.go
Towards https://github.com/giantswarm/giantswarm/issues/14140
When cluster upgrade is initiated, it takes a lot of time for the first node pool to start being upgraded, so for more than 20 minutes all `*Ready` conditions are unchanged, therefore it is considered that the cluster upgrade is completed.
This change mitigates the issue by increasing that waiting time from 20 to 45 minutes. See above linked issue for more details, a fix where entire upgrade process is more correctly reflected in conditions will be implemented later on.
=> Increase Upgrading condition threshold time

pkg/project/project.go, service/controller/azure_cluster_controller.go, service/controller/resource/azureclusterupgrade/error.go, service/controller/resource/azureclusterupgrade/resource.go
While not strictly necessary since AzureMachines aren't reconciled by any
operator, this makes future incremental development easier and keeps CRs more
consistent over time.
=> Ensure AzureMachine version labels are kept up-to-date

pkg/project/project.go, service/controller/resource/masters/create_master_instances_upgrading.go
AzureConfig status conditions / node states aren't updated anymore so
the information is not present there. When the tenant cluster nodes are
fetched anyway, it's best to use fresh information from them.
=> Don't rely on old CR's status conditions on upgrade

service/controller/resource/capzcrs/create.go, service/controller/resource/capzcrs/testdata/case-0-Simple-AzureConfig-migration-to-create-CAPI-CAPZ-CRs_AzureCluster.golden, service/controller/resource/capzcrs/testdata/case-0-Simple-AzureConfig-migration-to-create-CAPI-CAPZ-CRs_Cluster.golden, service/controller/resource/capzcrs/testdata/simple_azureconfig.yaml
For some reason this was missing. Needed when upgrading from
pre-nodepool cluster to nodepool cluster.
=> Copy AzureConfig cluster description to Cluster

service/controller/resource/capzcrs/create.go, service/controller/resource/capzcrs/testdata/case-0-Simple-AzureConfig-migration-to-create-CAPI-CAPZ-CRs_Cluster.golden
This annotation is used to signal that the cluster is being upgraded to the node pools release for the first time. It is then used to set conditions to appropriate values (to distinguish between new and existing clusters when seeing some Cluster CR for the first time).
It was incorrectly set as label :see_no_evil:
=> Fix first node pool upgrade annotation

CHANGELOG.md, pkg/project/project.go, service/controller/resource/clusterconditions/conditionupgrading.go
The `Upgrading` condition was being overwritten and it was always `UpgradeNotStarted`. With this change, we only set it to `UpgradeNotStarted` when the condition is `Unknown`. If it was already set to `False`, we keep it as is.
=> Don't set 'Upgrading' condition Reason when it was already False

service/controller/resource/azureclusterconditions/create.go
I was seeing some errors like
```
E 11/19 16:22:43 /apis/infrastructure.cluster.x-k8s.io/v1alpha3/namespaces/org-giantswarm/azureclusters/z70dw failed to reconcile | operatorkit/v4/pkg/controller/controller.go:305 | controller=azure-operator-azurecluster-controller | event=update | loop=7 | version=215891351
/go/pkg/mod/github.com/giantswarm/operatorkit/v4@v4.0.0/pkg/controller/controller.go:502
/go/pkg/mod/github.com/giantswarm/operatorkit/v4@v4.0.0/pkg/controller/controller.go:537
/go/pkg/mod/github.com/giantswarm/operatorkit/v4@v4.0.0/pkg/resource/wrapper/metricsresource/basic_resource.go:43
/go/pkg/mod/github.com/giantswarm/operatorkit/v4@v4.0.0/pkg/resource/wrapper/retryresource/basic_resource.go:64
/go/pkg/mod/github.com/giantswarm/backoff@v0.2.0/retry.go:23 …
```
=> Don't error when k8s API returns conflict while saving CR status

CHANGELOG.md, pkg/tenantcluster/cached.go, pkg/tenantcluster/error.go, pkg/tenantcluster/factory.go, service/controller/azure_machine_pool.go, service/controller/cluster.go, service/controller/machine_pool.go, service/controller/resource/clusterownerreference/resource.go, service/controller/resource/clusterupgrade/create.go, service/controller/resource/machinepoolupgrade/lastdeployedreleaseversion.go, service/controller/resource/nodepool/create_cordon_old_workers.go, service/controller/resource/nodepool/create_drain_old_worker_nodes.go, service/controller/resource/nodepool/create_terminate_old_workers.go, service/controller/resource/nodepool/create_wait_for_nodes_to_become_ready.go, service/controller/resource/nodepool/delete.go, service/controller/resource/workermigration/resource.go
While trying to connect to the tenant cluster k8s API we return errors like these
```
D 11/19 10:20:27 /apis/cluster.x-k8s.io/v1alpha3/namespaces/org-giantswarm/clusters/8t2uh clusterupgrade tenant API not available yet | azure-operator/v5/service/controller/resource/clusterupgrade/create.go:138 | controller=azure-operator-cluster-controller | event=update | loop=25 | version=215792872
/root/project/pkg/tenantcluster/factory.go:49
/go/pkg/mod/github.com/giantswarm/tenantcluster/v3@v3.0.0/pkg/tenantcluster/tenantcluster.go:62
timeout error: timeout error: waiting secrets, selector = "giantswarm.io/certificate=api, giantswarm.io/cluster=8t2uh"
```
```
D 11/19 10:20:27 /apis/cluster.x-k8s.io/v1alpha3/namespaces/org-giantswarm/clusters/8t2uh clusterupgrade tenant API not available yet | …
```
=> Cache tenant cluster k8s client look up and avoid errors if not ready yet

CHANGELOG.md, pkg/project/project.go, service/controller/azure_config.go, service/controller/azure_machine_pool.go, service/controller/resource/ipam/azure_machinepool_subnet_persister.go, service/controller/resource/ipam/azure_machinepool_subnet_releaser.go, service/controller/resource/ipam/create_test.go, service/controller/resource/ipam/delete.go, service/controller/resource/ipam/nop_releaser.go, service/controller/resource/ipam/resource.go, service/controller/resource/ipam/spec.go
When deleting node pool, the subnet allocation must be released in order
to make it available for later node pools.
This change adds an interface for `Releaser` and NOP implementation for
AzureConfig (because cluster resource allocations are released on
deletion automatically) and default implementation for
`AzureMachinePool` which removes the allocated subnet from
`AzureCluster` subnets.
=> Implement releasing of allocated subnet on deletion

CHANGELOG.md, service/controller/azure_config.go, service/controller/azure_machine_pool.go, service/controller/resource/ipam/azure_config_checker.go, service/controller/resource/ipam/azure_machinepool_subnet_checker.go, service/controller/resource/ipam/azure_machinepool_subnet_persister.go, service/controller/resource/ipam/azure_machinepool_subnet_releaser.go, service/controller/resource/ipam/create.go, service/controller/resource/ipam/create_test.go, service/controller/resource/ipam/delete.go, service/controller/resource/ipam/nop_releaser.go, service/controller/resource/ipam/resource.go, service/controller/resource/ipam/spec.go, service/controller/resource/ipam/test_checker.go
As a preparation for fixing subnet releasing on deletion of node pool,
refactor `ipam.Check()` to return allocated subnet if it exists.
=> Refactor ipam.Check() to return existing subnet

CHANGELOG.md, service/controller/azure_config.go, service/controller/azure_machine_pool.go, service/controller/resource/ipam/azure_config_checker.go, service/controller/resource/ipam/azure_machinepool_subnet_checker.go, service/controller/resource/ipam/azure_machinepool_subnet_persister.go, service/controller/resource/ipam/azure_machinepool_subnet_releaser.go, service/controller/resource/ipam/create.go, service/controller/resource/ipam/create_test.go, service/controller/resource/ipam/delete.go, service/controller/resource/ipam/nop_releaser.go, service/controller/resource/ipam/resource.go, service/controller/resource/ipam/spec.go, service/controller/resource/ipam/test_checker.go
* Refactor ipam.Check() to return existing subnet (#1181)
As a preparation for fixing subnet releasing on deletion of node pool,
refactor `ipam.Check()` to return allocated subnet if it exists.
* Implement releasing of allocated subnet on deletion (#1183)
When deleting node pool, the subnet allocation must be released in order
to make it available for later node pools.
This change adds an interface for `Releaser` and NOP implementation for
AzureConfig (because cluster resource allocations are released on
deletion automatically) and default implementation for
`AzureMachinePool` which removes the allocated subnet from
`AzureCluster` subnets.
Co-authored-by: Jose Armesto <github@armesto.net>
=> Release allocated node pool subnet on deletion

service/controller/key/key.go
Moved regexp MustCompile at global package level to avoid doing it everytime we call the key function
=> Moved regexp initialization at package global level

CHANGELOG.md, client/azure_client_set.go, client/factory.go, pkg/project/project.go, service/controller/resource/workermigration/create.go, service/controller/resource/workermigration/create_test.go, service/controller/resource/workermigration/internal/azure/api.go, service/controller/resource/workermigration/internal/azure/spec.go, service/controller/resource/workermigration/internal/mock_azure/api.go, service/controller/resource/workermigration/security_groups.go
Due to change prevention in network security group rules (to guard
customers' custom rules) the firewall rules don't get updated on cluster
upgrade and therefore the destination CIDR for some rules is wrong.
This change implements a migration path to replace built-in worker
subnet CIDR with VNET one.
=> Implement migration for worker network fw rules

CHANGELOG.md, client/azure_client_set.go, client/factory.go, service/controller/resource/workermigration/create.go, service/controller/resource/workermigration/create_test.go, service/controller/resource/workermigration/internal/azure/api.go, service/controller/resource/workermigration/internal/azure/spec.go, service/controller/resource/workermigration/internal/mock_azure/api.go, service/controller/resource/workermigration/security_groups.go
Due to change prevention in network security group rules (to guard
customers' custom rules) the firewall rules don't get updated on cluster
upgrade and therefore the source and destination CIDR for some
rules is wrong.
This change implements a migration path to replace built-in worker
subnet CIDR with VNET one.
=> Implement migration for worker network fw rules (#1193)

CHANGELOG.md, client/azure_client_set.go, client/factory.go, pkg/project/project.go, service/controller/azure_config.go, service/controller/resource/workermigration/create.go, service/controller/resource/workermigration/internal/azure/api.go, service/controller/resource/workermigration/internal/azure/spec.go, service/controller/resource/workermigration/internal/mock_azure/api.go, service/controller/resource/workermigration/resource.go, service/controller/resource/workermigration/security_groups.go
As part of preparation work towards HA masters the etcd LB was changed
from internal to external. This has the effect that control plane
cluster's clients are arriving from different source IPs and these must
be now updated into etcd LB ingress rules when upgrading a pre-NP
cluster.
=> Migrate master's security group rules on upgrade 

CHANGELOG.md, client/azure_client_set.go, client/factory.go, service/controller/azure_config.go, service/controller/resource/workermigration/create.go, service/controller/resource/workermigration/internal/azure/api.go, service/controller/resource/workermigration/internal/azure/spec.go, service/controller/resource/workermigration/internal/mock_azure/api.go, service/controller/resource/workermigration/resource.go, service/controller/resource/workermigration/security_groups.go
As part of preparation work towards HA masters the etcd LB was changed
from internal to external. This has the effect that control plane
cluster's clients are arriving from different source IPs and these must
be now updated into etcd LB ingress rules when upgrading a pre-NP
cluster.
=> Migrate master's security group rules on upgrade  (#1200)

go.mod, go.sum, helm/azure-operator/templates/configmap.yaml
It doesn't make sense to inject the DNS from the installations repo.
All versions of azure operator should send data to the same project in sentry otherwise having a central error collector doesn't make sense.
For this reason I harcdoded the DSN in the helm chart.
I also bumped to latest microerror
=> Hardcode sentry DSN because it makes no sense to inject it

CHANGELOG.md, go.mod, go.sum, pkg/project/project.go, service/controller/azure_machine_pool.go, service/controller/resource/azuremachineconditions/create.go, service/controller/resource/clusterreleaseversion/checkupgradeprogress.go, service/controller/resource/nodepool/resource.go
Towards https://github.com/giantswarm/giantswarm/issues/14140
`Cluster` `Upgrading` condition is being updated based on `release.giantswarm.io/last-deployed-version` annotation (by comparing it to desired release version).
This fixes how the annotation is updated, and it waits for all node pools to be upgraded before setting/updating the annotation on the `Cluster` CR. That will make `Cluster` `Upgrading` condition to switch from `True` to `False` only when all node pools are upgraded.
=> Fix incorrect Upgrading condition transition from True to False

CHANGELOG.md, pkg/project/project.go, service/controller/resource/azureconfig/create.go
Towards: https://github.com/giantswarm/giantswarm/issues/14893
This PR avoids the change of Availability Zones in the AzureConfig CR when upgrading from 12.x to 13.x
=> Avoid AZ override

CHANGELOG.md, service/controller/resource/azureconfig/create.go
this is the same fix we applied to 5.0.x here https://github.com/giantswarm/azure-operator/pull/1240
=> Backported fix for AZ keep

CHANGELOG.md, service/controller/resource/azuremachinepoolconditions/create.go, service/controller/resource/clusterupgrade/create.go
Towards https://github.com/giantswarm/giantswarm/issues/15156
What's in the box:
- Fixes issue where API conflict error happens in `azuremachinepooolconditions` handler when updating `AzureMachinePool` CR.
- Fixes issue where, during cluster upgrade, workload cluster API call fails due to API being unavailable.
=> Fix catching k8s API errors

CHANGELOG.md, service/controller/azure_config.go, service/controller/resource/ipam/virtualnetwork_collector.go, service/service.go
Towards: https://github.com/giantswarm/giantswarm/issues/15264
this PR enforces the fact that the management cluster's address space is not available for workload clusters.
=> Ensure the MC's network space is never used for WCs

CHANGELOG.md, service/controller/resource/nodepool/create_scale_workers.go
Towards: https://github.com/giantswarm/giantswarm/issues/15281
Instead of using the `MachinePool` replicas field to calculate the size of the node pool when doubling it, use the current number of nodes.
=> Fix scaling up node pool VMSS during an upgrade

service/controller/azurecluster/controller.go, service/controller/azurecluster/error.go, service/controller/azureconfig/controller.go, service/controller/azureconfig/error.go, service/controller/azuremachine/controller.go, service/controller/azuremachine/error.go, service/controller/azuremachinepool/controller.go, service/controller/azuremachinepool/error.go, service/controller/cluster/controller.go, service/controller/cluster/error.go, service/controller/machinepool/controller.go, service/controller/machinepool/error.go, service/controller/resource/spark/create.go, service/controller/resource/spark/resource.go, service/controller/unhealthynode/controller.go, service/controller/unhealthynode/error.go, service/service.go
This change moves each controller watching a given CR to its own
package. Refactoring of handlers will follow this.
Towards https://github.com/giantswarm/giantswarm/issues/14403
=> Move controllers to own packages

CHANGELOG.md, service/controller/key/key.go
Towards: https://github.com/giantswarm/giantswarm/issues/15372
this PR removes the explicit check for azure location == `germanywestcentral` and delegates availability zones check to the admission controller
=> Remove check for `germanywestcentral` region

CHANGELOG.md, go.mod, go.sum, pkg/project/project.go
Fixes https://github.com/giantswarm/giantswarm/issues/15297
What's in the box:
- Bump `conditions-handler` to v0.2.1 to include `ReplicasReady` fix from https://github.com/giantswarm/conditions-handler/pull/20
=> Bump conditions-handler to v0.2.1

CHANGELOG.md, service/controller/azureconfig/handler/volumebindingmigration/resource.go
The `volumebindingmigration` handler fails when there is no Kubernetes API available, blocking all the following handlers in the same controller from being executed.
This slows down cluster creation by a few minutes.
This PR adds a specific check for `Api not available` error and allows the following handlers to run normally even when there is no API available.
The  `volumebindingmigration` runs at every reconciliation loop so this is not creating any issue.
=> handle api not available case

go.mod, go.sum
`v0.4.12-gsalpha2` had a typo that was fixed in `v0.4.12-gsalpha3`
=> Update capz dependency

CHANGELOG.md, service/controller/azurecluster/handler/azureclusteridentity/create.go
Towards: https://github.com/giantswarm/giantswarm/issues/15602
this PR adds the migration logic needed to populate the `SubscriptionID` field of the `AzureCluster` CR based on the legacy organization secret
=> Ensure `AzureCluster` CR has the `SubscriptionID` field set.

pkg/handler/ipam/azure_machinepool_subnet_collector.go, pkg/project/project.go, service/controller/azurecluster/handler/subnet/resource.go
Don't panic if AzureCluster CR has a subnet without defined CIDBlocks.
While this is not necessarily strictly valid in all use cases, the code
should still handle the situation gracefully.
=> Don't panic on unallocated subnet entries

pkg/helpers/azuremachine.go, service/controller/azuremachine/handler/azuremachinemetadata/create.go
This handler was calling `Update` on the `AzureMachine` CR at every reconciliation loop, regardless of any changes being made to the CR.
This triggered a loop in the handler that was running in an infinite sequence.
This PR check for changes in the CR and avoid saving if there isn't any
=> avoid saving the azuremachine CR too often

CHANGELOG.md, service/controller/azuremachinepool/handler/nodepool/template/template.go
Towards: https://github.com/giantswarm/giantswarm/issues/15845
The `NodePool` handler compares the desired ARM deployment with the latest ARM deployment supplied to check if there are any changes that require the deployment to be updated.
One of the fields that is compared is the `scaling` field, that contains the min, max and current number of replicas for the NP.
When we first submit the deployment (new node pool) the "current" field is set to the same value as the "min" field.
From that moment on, if "min" != "max" (i.e. autoscaling is enabled) the "current" field is not reliable any more, because the autoscaler can change it any time.
That means that everytime the cluster autoscaler changed the size of a NP, azure operator considered the node pool deployment to be out of date and …
=> Avoid overriding the NP size when the scaling is changed by autoscaler.

CHANGELOG.md, service/controller/azuremachinepool/handler/nodepool/create_scale_workers.go, service/controller/machinepool/handler/machinepoolupgrade/lastdeployedreleaseversion.go
Towards: https://github.com/giantswarm/giantswarm/issues/15884
this PR addresses 2 problems:
1. upgrading node pools with zero replicas didn't ever finish
2. the upgrade conditions didn't work reliably for autoscaling node pools
=> Fix upgrade

.circleci/config.yml, .golangci.yml, CHANGELOG.md, go.mod, go.sum, pkg/credential/credential.go, pkg/credential/credential_test.go
This PR for version 5.5:
- Swaps MC and WC tenants in multi tenant azure clients
- Bumps architect to 2.7.0
- Disables gofmt to avoid big refactoring in this fix on an old release
=> Fix multi tenant auth

CHANGELOG.md, service/controller/azuremachinepool/handler/nodepool/create_wait_for_nodes_to_become_ready.go
This PR changes the upgrade strategy to avoid deadlocks during upgrade of spot instances node pools if there is no capacity to double the node pool size.
=> Don't wait for new workers to be up during spot instances NP upgrades

CHANGELOG.md, client/azure_client_set.go, client/factory.go, client/organization_factory.go, go.mod, go.sum, service/controller/azuremachinepool/handler/nodepool/delete.go
When deleting a node pool, we did not delete the role assignment created to use managed identity.
That meant it was impossible to re-create a node pool with the same name (because role assignment creation used to fail).
This PR aims at solving this issue by deleting the role assignment when deleting a node pool
=> When deleting a node pool, also delete the VMSS role assignment.

CHANGELOG.md, service/controller/azureconfig/handler/blobobject/desired.go, service/controller/azureconfig/handler/masters/deployment.go, service/controller/azuremachinepool/handler/cloudconfigblob/create.go, service/controller/azuremachinepool/handler/nodepool/create.go, service/controller/azuremachinepool/handler/nodepool/create_deployment_uninitialized.go, service/controller/azuremachinepool/handler/spark/create.go
Towards https://github.com/giantswarm/giantswarm/issues/17180
In the `apimachinery` version that we currently depend on, `errors.Is*` functions use a switch/case to check error type. In release `v0.19.0` onwards it uses `errors.As`, which takes into account the wrapped error. Until we upgrade to this release, we need these changes to actually check using the wrapped error.
=> Check error using wrapped error

CHANGELOG.md, helm/azure-operator/values.yaml
I don't know how shit works, so [I deleted the wrong values](https://github.com/giantswarm/azure-operator/pull/1439/files). I'm bringing them back with a twist. Instead of defaulting to quay.io like before, I keep defaults as empty strings to make it less confusing. All these values will be overwritten by our deployment pipeline.
=> Bring back default helm values

CHANGELOG.md, pkg/handler/nodes/state/error.go, pkg/handler/nodes/state/funcs.go, pkg/handler/nodes/state/funcs_test.go, pkg/label/label.go, service/controller/azureconfig/handler/masters/create_master_instances_upgrading.go, service/controller/azuremachinepool/handler/nodepool/create.go, service/controller/azuremachinepool/handler/nodepool/create_scale_workers.go
Towards: https://github.com/giantswarm/giantswarm/issues/17758
This PR adds some checks in the azure machine pool's `node` resource in order to recover from situations where the azure machine pool state machine is in an unknown state.
See https://github.com/giantswarm/giantswarm/issues/17763
=> Avoid vmss upgrade stuck

CHANGELOG.md, service/controller/cloudconfig/master_template.go, service/controller/cloudconfig/worker_template.go, service/controller/templates/ignition/azure-udev-rules.go
`/boot` automount currently fails because the udev rules are missing TAG=systemd on azure storage boot device.
This is fixed upstream with https://github.com/kinvolk/init/pull/41.  Until that change is merged and in the flatcar base image, this change is required to fix the automount issue.
=> Fix udev rules to fix /boot automount 

CHANGELOG.md, service/controller/azurecluster/handler/azureclusteridentity/create.go, service/controller/azurecluster/handler/azureclusteridentity/naming.go
Towards: https://github.com/giantswarm/giantswarm/issues/18171
Since version 5.7.1 newly created azureclusteridentity CRs were referencing the secret in a wrong namespace.
This PR fixes that error.
Tested, works fine
=> Fix namespace in secret reference of `AzureClusterIdentity`.

CHANGELOG.md, pkg/project/project.go, service/controller/machinepool/handler/machinepoolupgrade/resource.go
Towards https://github.com/giantswarm/giantswarm/issues/18210
Spark CR release label is not updated when we upgrade a cluster. Until now that was not an issue, because we did not use Spark CR release label anywhere.
After merging new Spark CR webhook handler in azure-admission-controller https://github.com/giantswarm/azure-admission-controller/pull/279, this issue will mean that some older Spark CRs will be ignored by azure-admission-controller. ATM not even that should cause any issues, but for the sake of keeping our CRs in a correct state, here's a little fix.
=> Update Spark release label when cluster is upgraded

CHANGELOG.md, pkg/project/project.go, service/controller/cloudconfig/cloud_config.go
Towards: https://github.com/giantswarm/roadmap/issues/554
Newest cluster operator stores the encryption secret in the org namespace. With this PR we check for the secret by label, ignoring the namespace.
=> Cluster operator master

CHANGELOG.md, service/controller/azuremachinepool/handler/nodepool/create.go
When we are upgrading a cluster we ensure if the master node is upgraded before we move on with node pools.
In a previous release we changed the way we check this situation, by looking to the WC k8s API as well.
During cluster creation this leads to runtime errors in azure operator, because master is not up and thus the API is down.
This PR considers this case and avoids erroring. 
End goal is to avoid useless `OperatorKitErrorRateTooHigh` alerts.
=> Better error checking

CHANGELOG.md, helm/azure-operator/templates/rbac.yaml, service/controller/azurecluster/controller.go, service/controller/azurecluster/handler/azureclusterconfig/create.go, service/controller/azurecluster/handler/azureclusterconfig/delete.go, service/controller/azurecluster/handler/azureclusterconfig/error.go, service/controller/azurecluster/handler/azureclusterconfig/resource.go
Towards: https://github.com/giantswarm/giantswarm/issues/20174 and https://github.com/giantswarm/roadmap/issues/646
Despite the fact the `AzureClusterConfig` CR is unused since release 16.1.0, to deal with upgraded clusters that already had that CR we need to bump the `cluster-operator` version label in `AzureClusterConfig` to avoid the legacy cluster operator and the new one fighting against default apps.
This PR does just that.
=> Azureclusterconfig

renovate.json
Trying `renovate` feature to exclude dependencies from getting automatic updates. If this works I'll make a PR so this is applied to all giantswarm repositories. 
We want to control CAPI upgrades instead of receiving automatic PR's to upgrade.
=> Exclude capi deps

CHANGELOG.md, pkg/label/label.go, service/controller/azuremachinepool/handler/nodepool/create_scale_workers.go, service/controller/azuremachinepool/handler/nodepool/deployment.go, service/controller/azuremachinepool/handler/nodepool/template/main.json, service/controller/azuremachinepool/handler/nodepool/template/parameters.go, service/controller/azuremachinepool/handler/nodepool/template/template.go, service/controller/cloudconfig/worker_template.go, service/controller/key/key.go
Towards: https://github.com/giantswarm/roadmap/issues/845
This PR makes nodes in a node pool roll automatically when there is a switch between groups v1 and v2 or vice versa
=> Roll nodes if cgroups change

CHANGELOG.md, service/controller/azuremachine/handler/azuremachineconditions/conditionready.go
Towards:  https://github.com/giantswarm/giantswarm/issues/21366
`kubectl get azuremachine` shows a `Ready` column that displays data from the `status.ready` field.
We never update that field, but rather rely on the `Ready` condition in the status.
this PR sets the `status.ready` field to the same value as the `Ready` condition
=> Set `AzureMachine.Status.Ready` according to AzureMachine's Ready condition

CHANGELOG.md, service/controller/azurecluster/handler/azureclusteridentity/create.go, service/controller/azuremachinepool/handler/migration/deleteold.go, service/controller/machinepool/handler/migration/deleteold.go, service/controller/machinepoolexp/handler/migration/azuremachinepool.go, service/controller/machinepoolexp/handler/migration/machinepool.go, service/controller/machinepoolexp/handler/migration/resource.go, service/controller/machinepoolexp/handler/migration/testdata/case-0-Simple-MachinePool_AzureMachinePool.golden
During upgrades from 17.0.1 to latest azure operator master, the node pools's backing VMSSes were deleted and recreated.
There were a few reasons for that
- after being copied to the new apiVersions, the `machinePool` and `azureMachinePool` CRs were deleted. Despite the fact the finalizers were removed, it could happen that the controller did one last reconciliation loop for the deletion event. Solved by adding the pause annotations just before deleting the CR.
- the ownerReference on the `azureMachinePool` CR were correctly updated to point to the new machinePool apiVersion, but the uid of the machinepool was still the old one. This meant when the old machinePool (the experimental one) was deleted by azure-operator, `controller-manager` thought the new azuremachinepool was orphaned, and …
=> fix ownerReferences' uids during migration to non-exp

CHANGELOG.md, service/controller/azurecluster/handler/azureclusterconditions/create.go, service/controller/azurecluster/handler/subnet/resource.go, service/controller/azureconfig/handler/blobobject/desired.go, service/controller/azureconfig/handler/blobobject/resource.go, service/controller/cloudconfig/base_extension.go, service/controller/cloudconfig/cloud_config.go, service/controller/cloudconfig/master_template.go, service/controller/cloudconfig/types.go, service/controller/key/common.go
Towards: https://github.com/giantswarm/roadmap/issues/791
This PR enables the encryption-provider-operator to allow automated secret encryption key rotation on azure workload clusters.
+ a couple of hidden fixes here and there. 10 point to whoever finds em :stuck_out_tongue:
=> Encryption operator

CHANGELOG.md, service/controller/machinepool/handler/nodestatus/create.go
Towards: https://github.com/giantswarm/giantswarm/issues/22624
when a NP moved from > 0 to 0 replicas, the status never got updated.
With this PR it does.
```
$ kubectl --context=gs-godsmack -n org-giantswarm get machinepools v5ow3  -o yaml | yq .status                                                                         whitesbook: Wed Jun 29 13:32:02 2022
availableReplicas: 1
...
nodeRefs:
- name: nodepool-v5ow3-000000
uid: 7d2e3e09-99da-4caf-882f-d344235619e1
readyReplicas: 1
replicas: 1
```
scaled NP to zero replicas
```
$ kubectl --context=gs-godsmack -n org-giantswarm get machinepools v5ow3  -o yaml | yq .status                                                                         whitesbook: Wed Jun 29 13:41:07 2022
...
replicas: 0
```
=> Fix empty nodepool status

CHANGELOG.md, helm/azure-operator/templates/deployment.yaml, helm/azure-operator/templates/psp.yaml, helm/azure-operator/values.yaml
Towards https://github.com/giantswarm/roadmap/issues/256
Adds the runtime/default seccomp profile and sets more explicitly restrictive security contexts to comply with `restricted` Pod Security Standards.
=> Make `azure-operator` PSS restricted compliant

CHANGELOG.md, go.mod, go.sum
Towards: https://github.com/giantswarm/giantswarm/issues/22498
=> - Bump `k8scc` to enable `auditd` monitoring for `execve` syscalls.
